- test/parser/expect/heading/basic.txt
- test/parser/expect/heading/followed-by-block.txt
- test/parser/expect/heading/label.txt
- test/parser/expect/heading/leading-cr-lf.txt
- test/parser/expect/heading/leading-newline.txt
- test/parser/expect/heading/leading-whitespace.txt
- test/parser/expect/heading/nested-code-with-spaces.txt
- test/parser/expect/heading/nested-code-with-uppercase.txt
- test/parser/expect/heading/nested-markup.txt
- test/parser/expect/heading/nested-style.txt
- test/parser/expect/heading/preceded-by-block.txt
- test/parser/expect/heading/preceded-by-shorthand-list.txt
- test/parser/expect/heading/subsection.txt
- test/parser/expect/heading/subsubsection.txt
- test/parser/expect/heading/trailing-newline.txt
- test/parser/expect/heading/trailing-whitespace.txt
- test/parser/expect/heading/whitespace-before-colon.txt
- test/parser/expect/heading/words.txt
- test/parser/expect/section-contexts/nested-code-with-newline.txt
- test/parser/expect/section-contexts/permissive.txt
- test/parser/expect/section-contexts/titles-allowed-permissive.txt
- test/parser/expect/section-contexts/titles-allowed.txt
- test/parser/expect/section-contexts/titles-no-high-levels-permissive.txt
- test/parser/expect/section-contexts/titles-zero-not-allowed-permissive.txt
- test/parser/expect/section-contexts/two-titles-permissive.txt
- test/parser/expect/utf-8/label.txt
- test/parser/expect/warnings/multiple-with-bad-section.txt
- test/parser/expect/warnings/multiple.txt
- test/parser/test.ml
- test/print/print.ml
Just preparing for a squash-merge.
> Tests: fix printing of digest in Root_to_sexp

- test/html/test.ml
> Run tidy if installed, fail if it's not and we're in travis

- test/html/test.ml
Fixes https://github.com/ocaml/odoc/pull/190/files#r218243322 and checks if tidy is installed in the CI early.
> Fix tidy check bug. Fail early if tidy is not installed in CI.

- src/html/html_generator.ml
- src/html/html_generator.mli
- src/html/to_ml_html_tree.ml
- src/html/to_re_html_tree.ml
- test/html/expect/test_package+re/Type/index.html
> Fix label value separator in Reason syntax

- src/html/odoc__html.ml
> Expose Html.Url module.

- src/odoc/bin/main.ml
Fixes https://github.com/ocaml/odoc/pull/262#issuecomment-443858040.
> Fix output dir creation

- src/odoc/etc/odoc.css
See https://github.com/ocaml/odoc/issues/294.
> Rename Topics to Contents.

- package.json
- test/ci/install-deps.sh
- Use newer esy version
- Update syntax for resolution
> Fix travis builds using esy

- src/loader/doc_attr.ml
- test/compile/expect/ast.txt
- test/compile/expect/parser_errors.txt
> Fix reporting of locations in standalone comments

- src/loader/cmi.ml
- src/loader/cmi.mli
- src/loader/cmt.ml
- src/loader/cmti.ml
- src/loader/doc_attr.ml
- src/loader/odoc__loader.ml
- src/model/compat.ml
- src/model/ident_env.ml
- src/model/ident_env.mli
- src/odoc/support_files.ml
- test/html/test.ml
Further work needs to be done to support the new typesubst/modsubst constructors.
Fixes #304
> OCaml 4.08 compatibility

- README.md
- src/odoc/index.mld
- src/odoc/using-odoc.mld
Among other things closes #219
> Doc improvements

- src/xref/expand.ml
- test/html/cases/alias.ml
- test/html/cases/include2.ml
- test/html/expect/test_package+ml/Alias/X/index.html
- test/html/expect/test_package+ml/Alias/index.html
- test/html/expect/test_package+ml/Include2/index.html
- test/html/expect/test_package+re/Alias/X/index.html
- test/html/expect/test_package+re/Alias/index.html
- test/html/expect/test_package+re/Include2/index.html
- test/html/test.ml
Fixes #87
Also adds a test for this issue as well as one for Aliases as my first
attempt at this broke them.
> Remove docs when including modules

- CHANGES.md
- src/html/generator.ml
- test/html/cases/recent.mli
- test/html/expect/test_package+ml/Recent/index.html
- test/html/expect/test_package+re/Recent/index.html
This is #353 rebased on master.
> fix generated html for conjunctive types

- README.md
> docs: fix link to BsDoc in readme

- src/odoc/etc/odoc.css
Initial implementation of what's suggested in #422.
This should keep IE compatibility by keeping the "old" colors in addition to the css variables.
> Initial darkmode implementation

- src/xref2/subst.ml
> Fix classtype path substitution

- .travis.yml
- odoc.opam
It seems to be because of this change: 2025b1abb59fc40c878d6f34c8290cd22fe03e46
> CI: Install test dependencies

- odoc.opam
- src/document/generator.ml
- src/loader/cmi.ml
- src/loader/cmi.mli
- src/model/lang.ml
- src/xref2/compile.ml
- src/xref2/component.ml
- src/xref2/component.mli
- src/xref2/cpath.ml
- src/xref2/lang_of.ml
- src/xref2/lang_of.mli
- src/xref2/link.ml
- src/xref2/scratch.md
- src/xref2/test.md
- test/xref2/refs/refs.md
> Minor fixes

- src/parser/lexer.mll
- src/parser/parse_error.ml
- test/compile/cases/parser_errors.mli
- test/compile/expect/parser_errors.txt
Fixes https://github.com/ocaml/odoc/issues/476.
> Provide third-person aliases for @raise and @return

- Makefile
- odoc.opam
- src/model_desc/dune
- src/odoc/bin/dune
- src/odoc/dune
- src/xref2/dune
The CLI interface changes in 2.0.0.
Also, enable it on more libraries.
> Use Bisect-ppx 2.0.0 and enable it on more libraries

- src/loader/cmi.ml
- src/loader/cmt.ml
- src/loader/cmti.ml
- src/model/lang.ml
- src/xref2/env.ml
- src/xref2/lang_of.ml
- test/html/expect/test_package+ml/Labels/index.html
- test/html/expect/test_package+re/Labels/index.html
Fix https://github.com/ocaml/odoc/issues/464
> Check comment attached to extensions

- src/model/paths.ml
- src/model/paths.mli
- src/model_desc/paths_desc.ml
> Simplify paths_desc

- .github/workflows/build.yml
> CI: Cache esy builds

- src/parser/lexer.mll
The detected indentation of code blocks was not the same depending on line endings.
Here is a CI build on Windows that include this patch: https://github.com/Julow/odoc/runs/1285922231?check_suite_focus=true
> Handle CRLF line endings when computing indentation of code blocks

- src/model/ident_env.cppo.ml
Noticed by @Julow in #580 but not followed up.
> Fix loading of cmts with Tstr_primitive

- src/xref2/link.ml
- test/xref2/page_labels.t/page.mld
- test/xref2/page_labels.t/run.t
Should fix the "b0.b00.kit" part of #609
> Add page labels to env before resolving

- src/parser/lexer.mll
- src/parser/parse_error.ml
- src/parser/syntax.ml
- src/parser/token.ml
- test/html/expect/test_package+ml/Ocamlary/index.html
- test/html/expect/test_package+re/Ocamlary/index.html
- test/parser/expect/unsupported/center-alignment.txt
- test/parser/expect/unsupported/left-alignment.txt
- test/parser/expect/unsupported/right-alignment.txt
Open in favour of https://github.com/ocaml/odoc/pull/619#discussion_r587734198
> Add alignment syntax to parser

- src/odoc/etc/odoc.css
They might be a good idea but I didn't intend to push them yet!
> Revert CSS changes accidentally committed

- CHANGES.md
- src/xref2/component.ml
- src/xref2/component.mli
- src/xref2/env.ml
- src/xref2/env.mli
- src/xref2/ref_tools.ml
- test/xref2/references_to_pages.t/good_references.mli
- test/xref2/references_to_pages.t/run.t
Fixes https://github.com/ocaml/odoc/issues/752
> Fix unqualified references to pages

- src/odoc/compile.ml
- src/odoc/odoc_link.ml
- src/odoc/resolver.ml
- src/odoc/resolver.mli
- src/xref2/compile.ml
- src/xref2/component.ml
- src/xref2/component.mli
- src/xref2/env.ml
- src/xref2/env.mli
- src/xref2/link.ml
- src/xref2/type_of.ml
- test/xref2/ambiguous_label.t/run.t
- test/xref2/labels.t/run.t
- test/xref2/lib/common.cppo.ml
- test/xref2/subst/test.md
Ensures we only ever add items to the environment once.
> Better environment handling

- doc/odoc_for_authors.mld
I recently started using odoc and `.mld` files to write a manual for MDX.
I'm contributing to odoc's documentation in the hope it will help others such as myself getting famliar with its markup.
I wasn't too sure where to put this exactly. I believe it's on the right page but the organisation there got me a bit lost.
I'm happy to move it to another section if you think that would be best!
> Briefly document how to create cross page section link odoc markup

- .github/workflows/build.yml
- odoc.opam
So we don't forget them again!
> Add changes to opam files from opam-repository tests

- CHANGES.md
- odoc.opam
- src/loader/cmi.ml
- src/loader/cmti.ml
This is a refactor on top of #787 from @patricoferris to make it easier to review
> Add compatibility with OCaml 4.14

- src/xref2/env.ml
> Don't reuse ident_map in Env.open_signature

- odoc.opam
> Constrain version of yojson

- src/loader/cmi.ml
- src/xref2/compile.ml
- src/xref2/env.ml
- src/xref2/env.mli
- src/xref2/lang_of.ml
- src/xref2/test.md
- src/xref2/tools.ml
- src/xref2/type_of.ml
- test/xref2/recursive_modules.t/m.mli
- test/xref2/recursive_modules.t/run.t
- test/xref2/recursive_types.t/m.mli
- test/xref2/recursive_types.t/run.t
- test/xref2/subst/test.md
This is on top of the bugfix PR. The 'close environment' was causing many `Not_found` exceptions for various reasons, taking lots of time to resolve. This PR removes entirely the need to close an environment, thus fixing that class of bugs.
> Incremental compile environment

- doc/odoc_for_authors.mld
> Fix bogus doc (closes #852).

- src/html/generator.ml
> Remove impossible cases (links within *_nolink)

- odoc.opam
> Update version constraint on Dune

- src/odoc/bin/main.ml
Sort commands in sections and improve the documentation. It's https://github.com/ocaml/odoc/pull/903 without the new documentation page.
> Improvements to the CLI documentation

- src/xref2/component.ml
- src/xref2/tools.ml
- test/xref2/canonical_nested.t/main.ml
- test/xref2/canonical_nested.t/main__.ml
- test/xref2/canonical_nested.t/main__Container.mli
- test/xref2/canonical_nested.t/run.t
- test/xref2/subst/test.md
Fundamentally this just needs us to reresolve the paths when figuring out the shortest canonical path to use, but this is a little tricky to get right.
> Fix nested canonical modules

- src/loader/cmt.ml
fixing https://github.com/ocaml/odoc/issues/895
after some hint in previous PR https://github.com/ocaml/odoc/pull/934
> fix issue #895: incorrect output of method types

- Makefile
This removes seemingly outdated rules and make the Makefile more readable and usable as documentation.
Is there any user of these rules ?
> Remove duniverse rules from the Makefile

- CHANGES.md
> Changelog entry of #1019 belongs to the next release

- odoc-bench.opam
- odoc-parser.opam
- odoc.opam
https://github.com/ocaml/odoc/issues/1004#issuecomment-1756172987
> Update URLs in opam files

- doc/driver.mld
- dune
- odoc-bench.opam
The benchmarks are failing due to a missing dependency. I changed the benchmark script to avoid hidding errors.
> Fix and show benchmark errors

- .github/workflows/build.yml
- Makefile
See https://github.com/ocaml/dune/issues/3884 for some discussion about the problem / workaround
> Enable coverage of cram tests

- CHANGES.md
- src/model/lang.ml
- test/xref2/inherit_top_comment.t/file.ml
- test/xref2/inherit_top_comment.t/run.t
> Import top comment from top include of a hidden module

- doc/cheatsheet.mld
- doc/driver.mld
- doc/dune
- doc/odoc.mld
- doc/odoc_for_authors.mld
> Backport cheatsheet to the 2.4 branch

- doc/cheatsheet.mld
> Fix typo in cheatsheet: Backport to v2.4

- doc/odoc.mld
Initial suggestions to improve the `odoc` pages and make them consistent with the style guide.
> line editing for odoc.mld

- doc/odoc.mld
Testing how the first sentence looks bolded to make it stand out more. Also, the page index list looked strange to me, as it mostly just restated what the links said, so I turned them into sentences. Looking forward to your thoughts @panglesd!
> suggestions for page index (mostly)

- src/loader/ident_env.cppo.ml
This separates the item extraction from the handling of visibility and of the 'hidden' flag.
This should catch the bug fixed by https://github.com/ocaml/odoc/pull/1100
> Refactor Ident_env.extract_signature_type_items

- doc/interface.mld
Mostly formatting, but there was also some syntax tightening (removing unnecessary words), so please let me know if anything is inaccurate.
> Line editing interface.mld

- doc/dune.mld
Mostly minor formatting. Please review to ensure all is still accurate. 🙂
> Line editing for dune.mld

- doc/odoc_for_authors.mld
Mostly formatting and other line editing, but there are a few questions below for your review @panglesd.
> line editing for odoc_for_authors.mld

- odoc-parser.opam
- odoc.opam
Fix https://github.com/ocaml/odoc/issues/1199
> opam: Add strict constraints on OCaml < 5.3

- .gitignore
Add odoc driver output to gitignore
> Add odoc driver output to gitignore

- src/parser/test/test.ml
As a "getting my feet wet", I've added a single test case that wasn't already covered.
> Add test for delimited code block with meta and output
