ocaml/odoc

Makefile
odoc.opam

- The previous `make clean` did not work correctly in a Jbuilder workspace.
- The previous `make clean` failed if the repo was already clean.
The `jbuilder clean` command requires Jbuilder >= 1.0+beta10.

Use jbuilder clean in make clean

---

etc/odoc.css

`<i>` tags generated by `{i foo}` weren't rendered in italic. This patch simply applies the same treatment as `<b>` tags.
I checked by manually editing `odoc.css` in another project that the issue is fixed.

Force <i> font style to italic

---

.gitignore
odoc.opam
src/parser/jbuild
src/parser/lexer.mll
test/parser/expect/code-block/leading-newline-with-space.txt
test/parser/expect/code-block/leading-tab-two-different-indent.txt
test/parser/expect/code-block/leading-tab-two.txt
test/parser/expect/code-block/leading-tab.txt
test/parser/expect/code-block/leading-whitespace-two-cr-lf.txt
test/parser/expect/code-block/leading-whitespace-two-different-indent-rev.txt
test/parser/expect/code-block/leading-whitespace-two-different-indent.txt
test/parser/expect/code-block/leading-whitespace-two.txt
test/parser/expect/code-block/leading-whitespace.txt
test/parser/test.ml

Tries to address #133.
The implementation brings in `Str` module to split strings (since `split_on_chars` is available only since 4.04.0). Let me know if you have concerns.
I also wondered whether we need to specially handle weird spaces and tabs combo, but decided not to since I don't think there's a use case for that.

Handle leading whitespace on code blocks

---

src/parser/lexer.mll
test/parser/expect/code-block/leading-whitespace-with-empty-line.txt
test/parser/expect/code-block/leading-whitespace-with-whitespace-line-long.txt
test/parser/expect/code-block/leading-whitespace-with-whitespace-line-short.txt
test/parser/test.ml

See [this comment](https://github.com/ocaml/odoc/pull/134#issuecomment-383309586).

Fix empty lines handling on code blocks

---

src/parser/semantics.ml
test/parser/expect/section-contexts/two-titles-permissive.txt
test/parser/expect/warnings/multiple-with-bad-section.txt
test/parser/expect/warnings/with-error.txt
test/parser/test.ml

This PR relaxes the heading level restriction reported in #141 which affects many existing packages. It does not change the current behaviour in which (a) the heading levels in docstrings are clamped to the interval [2-4] and (b) only one level-1 heading is allowed in manual pages.
The current implementation had a bug which resulted in the produced HTML page being cut off after parsing the first level-1 heading.
Based on my research I concluded that the bug was caused by the fact that the HTML generation code assumed that there was only one `` `Title `` heading. Specifically the [To_html_tree.Top_level_markup.section_comment](https://github.com/rizo/odoc/blob/fd68d5b7a479cce21cf2353304178c9162c152a6/src/html/to_html_tree.ml#L842) function checks for section nesting by comparing levels. In …

Relax heading restriction

---

src/odoc/jbuild

See [this comment](https://github.com/ocaml/dune/issues/856#issuecomment-394868711).
This will generate `index.mld` and `manual_usage.mld` into `index.html` and `manual_usage.html` when generating docs via dune (`jbuilder build @doc` or `dune build @doc`).
Note that on the generated pages, there are some broken references, particularly from `index` to `manual_usage`, which is confusing. I'll take a look at it, but I think this PR should be mergeable on its own.

Add documentation stanza to generate mlds

---

src/odoc/html_page.ml

While working on https://github.com/ocaml/odoc/pull/166 I noticed that small mld pages did not produce any output because the formatter wasn't properly flushed.
This explicitly flushes the generated HTML output, even though in practice it should be automatically flushed given the relatively large output produced by HTML documents.

Always flush the HTML output.

---

src/odoc/bin/main.ml

Fixes https://github.com/ocaml/odoc/issues/181.
In addition I corrected some outdated help comments in compile command and added a log line to show the input/output paths while compiling.

Always use "page-" prefix when compiling mld files

---

.travis.yml

This would let docs fallback to ligature fonts if the user already has them, but not force them upon users who don't have them installed.
I put the 4 most common I've seen people use but more can be added (or some removed).
@rizo let me know if there's any important ligature fonts missing here!
And I can't remember @aantron's stance on this 🙈

Automatically support ligature fonts if installed

---

odoc.opam
test/html/expect/test_package+custom_theme,ml/Include/index.html
test/html/expect/test_package+custom_theme,ml/Module/index.html
test/html/expect/test_package+custom_theme,ml/Section/index.html
test/html/expect/test_package+custom_theme,ml/Val/index.html
test/html/expect/test_package+ml/Class/index.html
test/html/expect/test_package+ml/External/index.html
test/html/expect/test_package+ml/Functor/index.html
test/html/expect/test_package+ml/Include/index.html
test/html/expect/test_package+ml/Interlude/index.html
test/html/expect/test_package+ml/Markup/index.html
test/html/expect/test_package+ml/Module/index.html
test/html/expect/test_package+ml/Section/index.html
test/html/expect/test_package+ml/Stop/index.html
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+ml/Val/index.html
test/html/expect/test_package+ml/mld.html
test/html/expect/test_package+re/Class/index.html
test/html/expect/test_package+re/External/index.html
test/html/expect/test_package+re/Functor/index.html
test/html/expect/test_package+re/Include/index.html
test/html/expect/test_package+re/Interlude/index.html
test/html/expect/test_package+re/Markup/index.html
test/html/expect/test_package+re/Module/index.html
test/html/expect/test_package+re/Section/index.html
test/html/expect/test_package+re/Stop/index.html
test/html/expect/test_package+re/Type/index.html
test/html/expect/test_package+re/Val/index.html
test/html/expect/test_package+re/mld.html
test/html/test.ml

This requires pinning `markup` and `tyxml` for now:
```
opam pin add --dev-repo markup
opam pin add --dev-repo tyxml
```
The TyXML pin is needed because of a depopt from released of TyXML on Markup.ml. There is a breaking change in Markup.ml (I added the `` `Raw`` signal), but only the TyXML PPX depends on Markup.ml, and we don't use the PPX. cc @Drup.
cc @ostera, @rizo
Resolves #187.

Testing: commit pretty-printed HTML output for nicer git diffs

---

src/html/html_generator.ml
src/html/html_generator.mli
src/html/to_ml_html_tree.ml
src/html/to_re_html_tree.ml
test/html/expect/test_package+re/External/index.html
test/html/expect/test_package+re/Functor/index.html
test/html/expect/test_package+re/Interlude/index.html
test/html/expect/test_package+re/Markup/index.html
test/html/expect/test_package+re/Module/index.html
test/html/expect/test_package+re/Section/index.html
test/html/expect/test_package+re/Stop/index.html
test/html/expect/test_package+re/Type/index.html
test/html/expect/test_package+re/Val/index.html

As it turns out, label separators seem to be pretty uniform within each
syntax, so I figured I'd pull that out of the `Syntax.Type` submodule
and solve it once for all of them.
Can be specialized if need be, but solves the issue for now.
Work on #199
cc @ryyppy @aantron

Fix all label separators in Reason syntax

---

src/html/html_generator.ml
src/html/html_generator.mli
test/html/cases/nested.mli
test/html/expect/test_package+custom_theme,ml/Include/index.html
test/html/expect/test_package+custom_theme,ml/Module/index.html
test/html/expect/test_package+ml/Class/index.html
test/html/expect/test_package+ml/Functor/index.html
test/html/expect/test_package+ml/Include/index.html
test/html/expect/test_package+ml/Module/index.html
test/html/expect/test_package+ml/Nested/index.html
test/html/expect/test_package+ml/Stop/index.html
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Class/index.html
test/html/expect/test_package+re/Functor/index.html
test/html/expect/test_package+re/Include/index.html
test/html/expect/test_package+re/Module/index.html
test/html/expect/test_package+re/Nested/index.html
test/html/expect/test_package+re/Stop/index.html
test/html/expect/test_package+re/Type/index.html
test/html/test.ml

This PR reimplements https://github.com/ocaml/odoc/pull/175 in a similar way.
The main difference is in the generated markup, where `dl` tags are used for the nested item and its preamble documentation. Regular `div` tags are used for nested items without documentation.
Thanks to @trefis for the original effort!

Print preamble for nested items

---

src/odoc/etc/odoc.css

This makes small adjustments to the CSS based on the feedback I received for the current theme. 
Custom fonts are included here as an experiment, we'll include them as static files when https://github.com/ocaml/odoc/issues/155 is resolved.
Here're some examples of packages with this change: [order](
http://odis.io/odoc-demo/order/Order/index.html), [lwt](
http://odis.io/odoc-demo/lwt/Lwt/index.html), [fmt](
http://odis.io/odoc-demo/fmt/Fmt/index.html), [cmdliner](
http://odis.io/odoc-demo/cmdliner/Cmdliner/index.html) and [base](
http://odis.io/odoc-demo/base/Base/index.html).
CC @aantron @ostera @ryyppy

Add custom remote fonts. Small visual adjustments.

---

README.md

Added information about how to pin the `odoc` in ReasonML projects. I placed information below installation step because I don't want to change the maim installation section.
#195

Add info do Readme about pid odoc

---

.gitignore
.travis.yml
Makefile
esy.lock.json
package.json
test/ci/build.sh
test/ci/clean-scratch.sh
test/ci/install-deps.sh
test/ci/print-versions.sh

Opening this PR for visibility/referencing, but I'll be modifying the history heavily until I get something I'm comfortable with.
Setting up `esy` seemed straightforward, although adding dependencies one by one manually is always annoying.
This is missing a few things:
But so far I've managed to install the npm package locally and it runs alright 👍 
```sh
ostera/odoc λ make npm
esy install
info install 0.2.11
esy make build
dune build
esy release
info release 0.2.11
dune build
info Creating npm release
info Exporting ocaml-4.2.3005-a85217cf: done
info Configuring release
info Done!
ostera/odoc λ cd _release && npm --global install .
/usr/local/bin/odoc -> /usr/local/lib/node_modules/odoc/bin/odoc
> odoc@1.2.0 postinstall /usr/local/lib/node_modules/odoc
> node ./esyInstallRelease.js …
```

Setup NPM Packaging

---

src/html/documentation.ml
src/html/documentation.mli
src/html/html_tree.ml
src/html/html_tree.mli
src/odoc/bin/main.ml
src/odoc/html_fragment.ml
src/odoc/html_fragment.mli

This renames `root-uri` to `xref-base-uri` as suggested by https://github.com/ocaml/odoc/issues/27#issuecomment-427862082. And more importantly fixes a bug where the default value for this option resulted in out of bounds access.
@aantron this is a breaking change on the command-line interface level but I don't think anyone is using this in 1.3 yet.
CC @dbuenzli

Rename root-uri to xref-base-uri and fix empty string bug.

---

src/loader/cmi.ml
test/html/cases/bugs.ml
test/html/expect/test_package+ml/Bugs/index.html
test/html/expect/test_package+re/Bugs/index.html
test/html/test.ml

@lpw25, It looks like we can fix the assertion failure by simply not checking which constructor we have, since:
- We don't print it. Whatever the constructor is in `?(foo : bar some_option)` in the `.cmt` file, we print `?foo:bar` in the output, since we are using the `val` syntax of signatures, rather than the `let` syntax of structures.
- I think we can rely on the compiler to have unified the constructor with `option`.
The commit includes a test which reproduces the failure, if the fix is left out. The output looks right to me, as `let foo (type a) ?(bar : a opt) () = ()` should indeed generate `val foo : ?bar:'a -> unit -> unit`.
Fixes #101.

Fix #101, assertion failure on some optional arguments in structure items

---

Makefile
test/compile/cases/ast.mli
test/compile/cases/parser_errors.mli
test/compile/dune
test/compile/expect/ast.txt
test/compile/expect/parser_errors.txt

@rizo This PR is the test cases for the `odoc lint` command you proposed, ported to work with `odoc compile` instead (https://github.com/ocaml/odoc/pull/226#issuecomment-432717405). I set you as the author, because you wrote these tests. I want to commit them now, so I can make use of them in work I want to do next.
These tests will probably need some quality-of-life improvements for developers, but I'll make them as I go, as needed by (at least) me.

Port new error message tests from #226 to master

---

src/odoc/bin/main.ml
src/odoc/support_files.ml
src/odoc/support_files.mli

With this PR:
```
$ odoc support-files-targets
odoc.css
highlight.pack.js
```
~~The command has no options~~.
I assume this output is suitable for consumption. cc @dbuenzli, @rgrinberg (though I will/can make a PR to Dune to use this).
Resolves #174.
See also https://github.com/ocaml/odoc/issues/153#issuecomment-434551361.

Add odoc support-files-targets

---

src/odoc/etc/odoc.css

Fixes #245 on Chrome (https://github.com/ocaml/odoc/issues/245#issuecomment-438677135). Not sure if that's the same problem that @jorisgio originally reported on Firefox, as well. @jorisgio, could you pin this branch, `fix-exception-spacing`, and try it?
@rizo, I removed the CSS for indenting lines in declarations:
```diff
-/* Indent the second line in multiline spec definitions. */
-.spec:not(.type) > code {
-  display: block;
-  padding-left: 4ex;
-  text-indent: -4ex;
-}
-
-.spec.exception > code {
-  display: inline-block;
-}
```
They were causing the issue in Chrome.
We have to indent by laying out the specifications correctly during HTML generation. Doing it with CSS gives undesirable results. For example, sometimes I saw line breaks in the middle of `->`, making the declaration …

Fix exception spacing

---

src/html/html_generator.ml
src/html/html_generator.mli
src/loader/cmi.ml
src/loader/cmti.ml
src/model/lang.ml
src/model/maps.ml
src/xref/component_table.ml
src/xref/expand.ml
src/xref/name_env.ml
test/html/cases/type.mli
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Type/index.html

Fixes #105.
Typedtree represents mutually-recursive type declarations as lists of type declarations (of length two or more), but odoc breaks these up into individual declarations.
In this PR, I decided to associate a flag with each type declaration, which indicates whether it was first in its list when loaded. This is a similar representation to the compiler's `types.mli`. It might not be optimal for some future purposes, however, so we may need to refactor it later.
Right now, the flag is passed straight through odoc, and controls only what keyword is used to render the type declaration.
I plan to use this for `nonrec` as well (#249), but I suspect the cross-referencer will need some changes to work with `nonrec` fully. The cross-referencer currently manages to resolve mutually-recursive …

Print mutually-recursive types with "and"

---

src/odoc/bin/main.ml

Fixes https://github.com/ocaml/odoc/issues/171.

Create output directory when generating HTML.

---

src/odoc/etc/odoc.css

This adds styling to the records that matches that introduced in
c/s c3a8f709acaee7a19ca928b277bdcf072ba3579f
Fixes #260.

Fix styling of records to match variants

---

test/html/test.ml

Attempts to ~~fix~~ #213.
I plan to split the work in two parts:
Maybe it's better to split the second point in multiple commits to make review easier.

Test nested HTML pages

---

README.md
src/odoc/system-integrations.mld

After long playing around with the bash script used to drive odoc for
BuckleScript projects, I decided it could be turned into a cli tool,
npm-installable, that would do the same thing without requiring copying
files around or leaking how odoc needs to be orchestrated.
This could pave the way to a deeper integration with the BuckleScript
platform, perhaps in the future `bsdoc` can be absorbed into it.
So here I just replace the references to such script with references to
the tool instead.
Let me know what you think!
cc/ @aantron @trefis @ryyppy @bobzhang

Switch bash driver with bsdoc

---

src/odoc/bin/main.ml
src/odoc/targets.ml
src/odoc/targets.mli

Rather than duplicate output logic in the Target module, we
delete it and expose both cli arguments and logic from the compile
command for usage by the compile-targets command. This decreases
the probability of those getting out of sync. Closes #172.

Fix compile-targets.

---

src/odoc/bin/main.ml

Do not require -I directories to exist in `compile` command
(closes #35). Do not require the -o directory to exist in
`*-targets` commands (closes #170).
I have checked the transitive usage of `convert_directory` via `dst` a few lines below and I believe this to be correct.

Cli: be more lenient with directory existence.

---

src/html/generator.ml
test/html/expect/test_package+ml/External/index.html
test/html/expect/test_package+re/External/index.html

Closes #275 
This is how the ReasonReact docs would look like after this change:

render externals as function signature

---

src/odoc/bin/main.ml

A simple workaround until https://github.com/ocaml/odoc/issues/129 is properly implemented. Setting `ODOC_SYNTAX=re` before calling `dune build @doc` will generate docs with reason syntax.
CC @ryyppy

Read ODOC_SYNTAX env var in odoc html command.

---

src/odoc/bin/main.ml
src/odoc/depends.ml

Make it work on cmt files ~~and do not report the unit itself as as a dependency~~. Closes #162.

Fix odoc compile-deps.

---

src/odoc/compilation_unit.ml
src/odoc/page.ml
src/odoc/root.ml

This hopes to solve #281.
After these changes I hit the following:
```
PS C:\LocalDevelopment\revery> esy doc
ocamlopt .ppx/95c43a5e8eeb6d851e1995d1bca87765/ppx.exe (exit 2)
(cd C:/LocalDevelopment/revery/_esy/default/store/b/revery-37b15f89\default && C:/LocalDevelopment/.esy/3_/i/ocaml-4.7.1003-d6263879/bin\ocamlopt.opt.exe -o .ppx/95c43a5e8eeb6d851e1995d1bca87765/ppx.exe -I C:/LocalDevelopment/.esy/3_/i/ocaml-4.7.1003-d6263879/lib/ocaml\compiler-libs -I C:/LocalDevelopment/.esy/3_/i/opam__s__lwt__ppx-opam__c__1.2.1-8fb7029d/lib\lwt_ppx -I C:/LocalDevelopment/.esy/3_/i/opam__s__ocaml_migrate_parsetree-opam__c__1.2.0-a491cf88/lib\ocaml-migrate-parsetree -I C:/LocalDevelopment/.esy/3_/i/opam__s__ppx__derivers-opam__c__1.0-de0fe9e4/lib\ppx_derivers -I …
```

Use binary mode where needed

---

src/html/targets.ml
src/odoc/bin/main.ml
src/odoc/depends.ml
src/odoc/targets.ml
src/odoc/targets.mli

A few commits for `html-{targets,deps}`. 
1. Do not generate targets for modules that are between stop comments (#276). The sub-sub module problem mentioned in the issue remains though.
2. `html-{deps,targets}` do not segfault in presence of `odoc` pages. 
For now `html-deps` will simply output nothing which is certainly wrong. Didn't figure out what needs to be done yet, I'll open a new issue to track it once this is in.

Partially fix html cmds

---

CONTRIBUTING.md

This fixes an issue I had when I ran `make test` with my stock `tidy` binary shipped with MacOS.
Installing `tidy-html5` via `brew` made the tests green :-)

Update CONTRIBUTING file with tidy installation instructions

---

src/html/generator.ml
src/odoc/etc/odoc.css
test/html/cases/nested.mli
test/html/expect/test_package+ml/Nested/F/argument-1-Arg1/index.html
test/html/expect/test_package+ml/Nested/F/argument-2-Arg2/index.html
test/html/expect/test_package+ml/Nested/F/index.html
test/html/expect/test_package+ml/Nested/X/index.html
test/html/expect/test_package+ml/Nested/class-z/index.html
test/html/expect/test_package+ml/Nested/index.html
test/html/expect/test_package+ml/Nested/module-type-Y/index.html
test/html/expect/test_package+re/Nested/F/argument-1-Arg1/index.html
test/html/expect/test_package+re/Nested/F/argument-2-Arg2/index.html
test/html/expect/test_package+re/Nested/F/index.html
test/html/expect/test_package+re/Nested/X/index.html
test/html/expect/test_package+re/Nested/class-z/index.html
test/html/expect/test_package+re/Nested/index.html
test/html/expect/test_package+re/Nested/module-type-Y/index.html
test/html/test.ml

Currently the table of contents is only rendered for top-level modules. This PR implements the rendering for all nested items (modules, module types, classes, functors and functor parameters) and makes some other minor adjustments.
* Render TOC (if not empty) inside header in all nested pages.
* Fix a bug where functor arguments were listed in reverse order ([diff](https://github.com/ocaml/odoc/compare/master...rizo:render-nested-toc?expand=1#diff-46e526e8d708dd25c7f790e20662ad2eR1371)).
* Remove the `doc` CSS class from class items, to be consistent with other nested items ([diff](https://github.com/ocaml/odoc/compare/master...rizo:render-nested-toc?expand=1#diff-46e526e8d708dd25c7f790e20662ad2eL1171)).
* Render functor parameters as `ul` (and not as a `dl`).
* Extend the "nested" HTML …

Render TOC in nested pages

---

src/html/comment.ml
test/html/cases/markup.mli
test/html/expect/test_package+ml/Markup/index.html
test/html/expect/test_package+re/Markup/index.html

See https://github.com/ocaml/odoc/issues/297.

Add `modules` class to the ul generated by {!modules: ...} directive.

---

odoc.opam
src/odoc/fs.mli
src/parser/dune
src/parser/reference.ml
src/parser/syntax.ml

Same rationale as https://github.com/ocaml/odoc/pull/305. 
Here only the bind operator (`>>=`) was used and only at three specific points. I just inlined the bind definition.

Remove dependency on rresult.

---

odoc.opam
src/odoc/dune
src/odoc/fs.ml

Tools like odoc at the roots of the eco-system should be lean on deps. This removes one of them.
In this case it seems only `Bos.File.read` was being used. I added something that is functionally equivalent.

Remove dependency on bos.

---

package.json

As @ulrikstrid mentioned before, depending on `make` hinders
the build on Windows.
Also bump version number from 1.2.0 to match current tag 1.3.0

Remove make from esy build step

---

src/odoc/depends.ml
src/odoc/fs.ml
src/odoc/fs.mli

Make `html-deps` look recursively in the package directory for odoc files. Before this patch it only looked at the first level of the given package directory which is not what you want in practice. 
A lot of packages have a hierarchy in their install libdir (try e.g. `ls $(opam var odoc:lib)`). When you generate the `odoc` files you copycat that hierarchy. As mentioned `html-deps` would not lookup the hierarchy but only the first level of the hierarchy. For a package like `odoc` itself this would return an empty set of deps, which would then result in failures further down the pipeline.

html-deps: Fix package flatness assumption.

---

src/html/generator.ml
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Type/index.html

Before this PR, the code
https://github.com/ocaml/odoc/blob/96a970ce3092d80eaa1ff4ec683288995d4ff419/test/html/cases/type.mli#L120-L122
results in the output
```ocaml
type ('a, 'b) double_constrained = 'a * 'b constraint 'a = int and 'b = unit
```
which does not match the source syntax.
This PR changes the output to match.
In future work, I will (or hope to) add proper pretty-printing with newlines, including for this case.

Fix output of multiple type constraints

---

src/odoc/etc/odoc.css

The stylesheet was significantly changed since I created it and no longer represents my original design or one I would author.

odoc.css: Change copyright attribution.

---

src/html/generator.ml

Fixes #318.
This is a quick fix. A better version would make the argument mandatory instead of optional, to avoid such issues in the future.

theme-uri: propagate everywhere

---

src/html/generator.ml
test/html/cases/class.mli
test/html/expect/test_package+ml/Class/index.html
test/html/expect/test_package+ml/Nested/index.html
test/html/expect/test_package+re/Class/index.html
test/html/expect/test_package+re/Nested/index.html

Fixes #338. I tested this locally by generating the docs for Ppxlib_traverse_builtins and it seemed to have inserted the space.

generator: Add missing space before class name

---

src/html/generator.ml
test/html/expect/test_package+custom_theme,ml/Module/index.html
test/html/expect/test_package+ml/Functor/index.html
test/html/expect/test_package+ml/Module/index.html
test/html/expect/test_package+ml/Recent/index.html
test/html/expect/test_package+re/Functor/index.html
test/html/expect/test_package+re/Module/index.html
test/html/expect/test_package+re/Recent/index.html

All cases of module type definitions in both OCaml and Reason use an
equal sign to separate the identifier from the definitions.

Always use " = " separator for module type definitions

---

test/html/tidy.ml

macOS comes with tidy but it is an old version that does not support the `--mute` option. This leads to spurious test failures on macOS.
This adds a check to is_present_in_path that requires the available version of tidy support the mute configuration option before it will be used.

Check that tidy supports the mute option

---

src/model/maps.ml
src/xref/subst.ml

We have some files at janestreet where odoc was using over 40G of memory, this series of patch brings that back down to roughly 10G.
On these files odoc is about 5x slower though.
I expect the rewrite that @jonludlam is currently working on to improve the (resulting as well as preexisting) slowness issues.
In the meantime, these patches are necessary because odoc gets reliably OOM killed when ran from a build system.

Reduce memory usage

---

src/html/ML.ml
src/html/generator.ml
src/html/generator_signatures.ml
test/html/expect/test_package+custom_theme,ml/Module/index.html
test/html/expect/test_package+ml/Bugs/index.html
test/html/expect/test_package+ml/Class/index.html
test/html/expect/test_package+ml/Module/index.html
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Bugs/index.html
test/html/expect/test_package+re/Module/index.html
test/html/expect/test_package+re/Nested/F/index.html
test/html/expect/test_package+re/Type/index.html

#359 reloaded:
- it's closer to @dbuenzli's initial markup
- I also `<span>` type constructors and their parameters together
- the implementation is much cleaner.
- I've updated the testsuite!
The final result for the extreme example I was using doesn't look quite as nice:
But it's reasonable, and Daniel seems to thing the markup proposed here will be better in general, which I tend to agree with.
I'm considering including some special handling for extreme cases like the one in the screenshot, but that will wait until a later date.
I think that unlike #359 this is in a reasonable state and is ready for review.

Span things

---

src/html/generator.ml
src/html/generator_signatures.ml
test/html/cases/mld.mld
test/html/expect/test_package+ml/mld.html
test/html/expect/test_package+re/mld.html

Fixes https://github.com/ocaml/odoc/issues/294.
- Added `Generator.Top_level_markup.lay_out_page` – an entry point for HTML generation of pages. This function will produce HTML content for pages, the header element and the TOC.
- Introduced the `comment_state` type that is used to track the state for HTML generation of both signatures and mld files.
- `page_section_comment` implements the same logic as `section_comment` with some changes:
- The title heading is not included in TOC.
- The title heading and the following content (until the next heading or end) are placed into a header element. This is similar to signatures.
- The other headings and the following content are _not_ placed into section elements. I find this unnecessary for plain mld files. I also think we should simplify this …

HTML TOC for mld pages

---

src/html/generator.ml
test/html/cases/mld.mld
test/html/expect/test_package+ml/mld.html
test/html/expect/test_package+re/mld.html

Fixes https://github.com/ocaml/odoc/issues/365.
* Added paragraphs to the mld test.
* There's no point in using `finish_comment_state` for `acc_html` because without section elements we're appending elements, not consing.

Fixes paragraph ordering in HTML for mld pages.

---

src/parser/ast.ml
src/parser/lexer.mll
src/parser/parse_error.ml
src/parser/semantics.ml
src/parser/syntax.ml
src/parser/token.ml

Hi!
As I explained in ocaml/odoc#355, `Model.Comment` is a bit hard to obtain and understand and too strict and lossy on the input.
Some of this issues could be solved by changing `Model.Comment` with a bit of work. But I think that in the future, this will make similar issues harder to solve as Odoc codebase and language change.
This PR simplifies `Parser.Ast` to make it closer to the concrete syntax and simpler by delaying some parsing to `semantics.ml`:
- References are represented as strings
- `Raw_markup` targets can be any string or none.
- Keep concrete syntax used for lists
- Keep whitespaces (Only when a `Space` element is generated)
This PR also removes some uses of `Model` types, as @lpw25 suggested, but not all yet.
This PR is supposed to follow ocaml/odoc#351 but if this …

Simpler parser ast

---

src/parser/odoc_parser.ml
src/parser/odoc_parser.mli

This PR exposes the internal modules of the parser.
I figured that `Parser_.Ast` is a bit simpler than `Model.Comment` and a lot simpler to obtain.
It also contains more informations (eg. heading labels)
I also add `Parser.parse_comment_raw` that returns an `Ast.docs`.

Expose parser internals and add Parser.parse_comment_raw

---

src/odoc/env.ml

If we encounter End_of_file, we get uneven lists for roots and paths.

odoc/env: Fix bug in List.iter2 throwing Invalid_arg

---

src/html/targets.ml

Fixes the fact that generated files for modules beyond one level after the top level were not reported by `html-targets`. A similar fix is applied for module types (not reported in #276).
Please review carefully I don't claim I understand what I'm doing 😅. 
My approach was simply to realize that in subsub modules we would end up in [this `AlreadyASig` case](https://github.com/ocaml/odoc/blob/1843f89f769bd16147802414e1b0bf1d3a87d5ef/src/html/targets.ml#L77) and nothing was then being done. So I went in the `generator.ml` file and made a copy-cat what is being done [there](https://github.com/ocaml/odoc/blob/master/src/html/generator.ml#L1521-L1532) in that case which seems to work... 
Along the way I realized the same may happen for module types (I don't have a report for that though) so I …

Fix odoc html-targets (closes #276).

---

src/html/generator.ml
src/html/targets.ml
src/loader/cmti.ml
src/model/ident_env.cppo.ml
src/model/lang.ml
src/model/maps.ml
src/model/maps.mli
src/xref/component_table.ml
src/xref/name_env.ml
test/html/cases/recent.mli
test/html/expect/test_package+ml/Recent/X/index.html
test/html/expect/test_package+ml/Recent/index.html
test/html/expect/test_package+re/Recent/X/index.html
test/html/expect/test_package+re/Recent/index.html
test/html/test.ml

This PR will render the new syntactic elements as written in the mli files. This should fix #350 as it qualifies as 'minimal support'. We might want to consider removing the substituted modules and types entirely, depending on how these features end up being used.

Handle 4.08 module and type substitutions

---

src/model/compat.cppo.ml

The constraint in the cppo conditional compilation also expands to 4.10.0~dev as well, since it should work there too.
Closes #382
cc @jonludlam

Fix compilation on OCaml 4.09.0 beta2

---

src/parser/reference.ml
test/parser/expect/simple-reference/operator-with-colon.txt
test/parser/test.ml

Parser: handle colons in references to operators

---

src/model/error.ml
src/model/error.mli
src/odoc/bin/main.ml
src/odoc/compile.ml
src/odoc/compile.mli
src/odoc/html_fragment.ml
src/odoc/html_fragment.mli
src/odoc/html_page.ml
src/odoc/html_page.mli
test/compile/cases/parser_errors_fatal.mli
test/compile/dune
test/compile/expect/parser_errors_fatal.txt

Closes https://github.com/ocaml/odoc/issues/284
This PR adds the option `--warn-error` to turn warnings into errors.
It is implemented using a global flag and failing after warnings are printed.
This is the easier implementation I found and it has some problems:
- Very few warnings are accumulated before `shed_warnings` is called and the error is raised.
- It's a global variable that is very deep in the dependency chain
I also started looking into other ways that require refactoring:
- Passing the warning accumulator everywhere
It's how the parser works but makes the code very verbose and introduce a lot of diffs. (~300 adds)
- Change `Error.catch` to also "catch" warnings
This is also a lot of changes and requires to change the API of `Error` to avoid bad uses, which requires even more …

Option to turn warnings into errors

---

src/odoc/bin/main.ml
src/odoc/compilation_unit.ml
src/odoc/compilation_unit.mli
src/odoc/compile.ml
src/odoc/compile.mli
src/odoc/depends.ml
src/odoc/depends.mli
src/odoc/env.ml
src/odoc/fs.ml
src/odoc/fs.mli
src/odoc/html_fragment.ml
src/odoc/html_fragment.mli
src/odoc/html_page.ml
src/odoc/html_page.mli
src/odoc/or_error.ml
src/odoc/or_error.mli
src/odoc/page.ml
src/odoc/page.mli
src/odoc/root.ml
src/odoc/root.mli
src/odoc/targets.ml
src/odoc/targets.mli
src/xref/odoc_xref.ml
src/xref/odoc_xref.mli

Refactor error reporting to avoid exiting the program in library code.
Errors are propagated back to `odoc/bin/main.ml` by value and handled in an unified way.
Most of the changes are trivial but the patch is very invasive, exiting functions were very deep in the program.
Using exceptions can make the patch a little smaller but also harder as all exposed functions would need to catch them and there is a lot of them.
The exit status for some errors (marshalling) is now `1` instead of `2`. Is that an issue ?
I added the `Or_error` module that re-export `result` and define a bind operator. I didn't use `rresult` as it was removed in https://github.com/ocaml/odoc/pull/306.
Only the first commit is required for https://github.com/ocaml/odoc/pull/398

Don't exit in library code

---

src/odoc/bin/main.ml

I was pleased to see the PR to [add a flag for fatal warnings](https://github.com/ocaml/odoc/pull/398) to `odoc`. This will be really useful for linting documentation in CI. 
For our specific use-case in [`ocaml-ci`](https://github.com/ocurrent/ocaml-ci), it would be great to be able to trigger this feature even if it's not specified in Dune's `documentation` stanza. This PR adds an `ODOC_WARN_ERROR` environment variable to do just that :slightly_smiling_face:
Old API:
```shell
$ odoc compile --help
...
--warn-error
Turn warnings into errors.
```
New API:
```shell
$ odoc compile --help
...
--warn-error (absent ODOC_WARN_ERROR env)
Turn warnings into errors.
...
ENVIRONMENT
These environment variables affect the execution of compile:
ODOC_WARN_ERROR
Turn warnings into errors. See option …
```

Allow --warn-error to be set by an environment variable

---

src/html/generator.ml
src/html/targets.ml
src/loader/cmi.ml
src/loader/cmt.ml
src/loader/cmti.ml
src/model/compat.cppo.ml
src/model/ident_env.cppo.ml
src/model/lang.ml
src/model/maps.ml
src/model/maps.mli
src/xref/component_table.ml
src/xref/expand.ml
src/xref/name_env.ml
src/xref/resolve.ml
test/html/cases/bugs.ml
test/html/cases/bugs_pre_410.ml
test/html/expect/test_package+ml/Bugs/index.html
test/html/expect/test_package+ml/Bugs_pre_410/index.html
test/html/expect/test_package+re/Bugs/index.html
test/html/expect/test_package+re/Bugs_pre_410/index.html
test/html/test.ml

This moves us in the direction of using 4.10's data types everywhere - though it doesn't go quite as far as making the module names optional.

4.10 compatibility

---

src/odoc/etc/odoc.css

the original value (500) is too small, it will fallback to 400 and has no any visually different to normal text.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Fallback_weights

adjust default `font-weight` for bold text

---

src/html/generator.ml
src/html/generator_signatures.ml
test/html/cases/include_sections.mli
test/html/expect/test_package+ml/Include_sections/index.html
test/html/expect/test_package+ml/Include_sections/module-type-Something/index.html
test/html/expect/test_package+re/Include_sections/index.html
test/html/expect/test_package+re/Include_sections/module-type-Something/index.html
test/html/test.ml

Also, heading levels from the include are shifted to stay nested under the current level. That seems like the right default but perhaps we'll want to add a flag to disable that behavior in the future.
Fixes #412.
This didn't have an impact on the testsuite, so I'll add fresh tests exhibiting the behavior change tomorrow morning.

Add sections of inlined include to ToC

---

src/html/comment.ml
src/model/comment.ml
src/odoc/etc/odoc.css
test/html/cases/markup.mli
test/html/expect/test_package+ml/Markup/index.html
test/html/expect/test_package+re/Markup/index.html

This pr fixes #420 
Browsers does not style nested emphasis as expected (ie: emphasis should toggle italics on/off, not always on, depending on the context).
This PR add logic to `src/html/comment.ml` to annotate `<em>` at an odd level of nesting with the class `odd`. Nesting level is reset when crossing `<it>`tags. Then a few css rules are added to style adequately each case. 
Because this is an issue only for browser rendering, I chose to fix it at the renderer level.
Another choice may have been to fix it at the parser level, by adding an `int` argument to the ``` `Emphasis``` variant.

Issue 420 nested `<em>` tags not rendering properly in browsers

---

.travis.yml
src/loader/cmt.ml
src/loader/doc_attr.ml

OCaml 4.11.0~alpha1 is out. This PR fixes the compilation issues with this new version

OCaml 4.11 support

---

src/loader/cmi.ml
test/compile/cases/impl_only.ml
test/compile/dune

Fixes the small reproduction case in https://github.com/ocaml/odoc/issues/388
This fixes the crash but the output for classes is not great and should be
reworked.
The output for:
```ocaml
class foo =
object(o)
method test () = o
end
```
is:
```ocaml
method test : < test : unit -> 'a; .. > -> unit -> 'a
```

xref2: Fix stack overflow on classes

---

odoc.opam

- `fmt` is required by `document`
- `mdx` should be a test-dependency
- I changed "dev" to "with-test" because they are necessary to run the tests with `opam install -t`

Update deps in opam file

---

src/model/paths.ml
src/model/paths.mli
src/xref2/env.ml
test/cases/labels.mli
test/html/expect/test_package+ml/Labels/index.html
test/html/expect/test_package+re/Labels/index.html
test/html/test.ml

Fix https://github.com/ocaml/odoc/issues/448
This is especially useful for the top comments, which is attached to the compilation unit.

Don't ignore labels attached to signature items

---

test/xref2/lib/dune

Toploop is called, so this library can only be used in bytecode.

Eliminate opaque warning with xref2 test

---

src/xref2/compile.ml
src/xref2/errors.mli
src/xref2/expand_tools.ml
src/xref2/link.ml
src/xref2/scratch.md
src/xref2/test.md
src/xref2/tools.ml
src/xref2/tools.mli

As @jonludlam noticed, the Unresolved case is not much used and always correspond to the input value.
Use `result` instead, which will be convenient to show better errors.

xref2: Remove Tools.ResolvedMonad

---

src/document/url.ml
src/html/url.ml
src/model/paths.ml
src/model/paths_types.ml
src/xref2/component.ml
src/xref2/cpath.ml
src/xref2/lang_of.ml
src/xref2/link.ml
src/xref2/paths.md
src/xref2/subst.ml
src/xref2/test.md
src/xref2/tools.ml
test/print/print.ml
test/xref2/lib/common.cppo.ml
test/xref2/resolve/test.md

As discussed in the previous dev meeting. This fixes the expansion of a few modules, though it's not entirely clear why. We may well want to relax this condition in the future as many functor bodies can be expanded even if the argument is unresolved, as it's usually the case that the result is independent of the argument.

Disallow unresolved arguments to Apply

---

.travis.yml

`opam install --deps-only -t` won't install it, probably because it would install the released version of Odoc.

Travis: Fix Mdx dependency

---

src/odoc/bin/main.ml

This PR fixes a minor typo in the description of html-deps.

Typo in command name

---

src/document/generator.ml
test/cases/type.mli
test/html/expect/test_package+ml/Labels/index.html
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Labels/index.html
test/html/expect/test_package+re/Ocamlary/index.html
test/html/expect/test_package+re/Type/index.html
test/man/expect/test_package+ml/Type.3o

This adds support for documenting type extensions, as in:
```ocaml
type extensible +=
| Extension (** Documentation for {!Extension}. *)
| Another_extension (** Documentation for {!Another_extension}. *)
```
which gets rid of [a `TODO` in the document generator](https://github.com/ocaml/odoc/blob/master/src/document/generator.ml#L563). The approach taken is symmetric with that of variant cases.

document: support documentation and linking of type extensions

---

odoc.opam

Yojson is used to print Lang values to a format that can be post-processed.

Add missing test-dependency on Yojson

---

src/loader/doc_attr.ml
src/loader/odoc_loader.ml
src/loader/odoc_loader.mli
src/model/error.ml
src/model/error.mli
src/odoc/bin/main.ml
src/odoc/compile.ml
src/odoc/html_fragment.ml
src/odoc/odoc_link.ml
src/odoc/rendering.ml
src/xref2/dune
test/compile/expect/parser_errors_fatal.txt
test/xref2/refs/refs.md

Fix an uncaught exception with `--warn-error` and improve the code:
- Cleaner way of handling `--warn-error`
- Remove exceptions from the loader API. Handling of errors and warnings is cleaner and fits better with code for the first point.
- Remove `shed_warnings`. This means that all warnings are accumulated before an error is raised.

Improve handling of warnings

---

README.md
src/odoc/system-integrations.mld

This change update the bsdoc documentation url to its new
location.

Update bsdoc reference

---

src/document/generator.ml
src/model/lang.ml
src/model_desc/lang_desc.ml
src/xref2/compile.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/expand_tools.ml
src/xref2/lang_of.ml
src/xref2/link.ml
src/xref2/strengthen.ml
src/xref2/subst.ml
src/xref2/subst.mli
src/xref2/tools.ml
src/xref2/tools.mli
src/xref2/type_of.ml

OCaml expands `module type of` expressions early, and subsequent operations -- such as substitution, functor application and so on -- operate on the expansion rather than the `module type of` expression. Before this PR, odoc did not do this, which led to differences in expansions. For example, on the following code:
```ocaml
module type S = sig
module X : sig type t end
module type Y = module type of X
end
module X1 : sig type t type u end
module type T = S with module X := X1
```
OCaml produces
```ocaml
module type T = sig module type Y = sig type t end end
```
whereas odoc was producing
```ocaml
module type T = sig module type Y = sig type t type u end
```
This PR fixes this problem by expanding all `module type of` expressions present in the current cmt/cmti before doing anything else, …

Fix `module type of` expansions

---

src/document/url.mli
src/xref2/compile.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/find.ml
src/xref2/find.mli
src/xref2/link.ml
src/xref2/lookup_failures.ml
src/xref2/lookup_failures.mli
src/xref2/ref_tools.ml
src/xref2/test.md
src/xref2/tools.ml
src/xref2/tools.mli
test/xref2/refs/refs.md
test/xref2/subst/test.md

Adds a warning when a reference is ambiguous:
```
Reference to 't' is ambiguous. Please specify its kind: val-t, type-t.
```
Adds the notion of "implicit warning" which may not be well defined/named and complicated error handling a bit in xref2.
The interface of `Find` needed to be changed.

xref2: Ambiguous reference warning

---

src/html/dune
src/html/generator.ml
src/latex/dune
src/latex/generator.ml
src/manpage/dune
src/manpage/generator.ml
src/model/comment.ml
src/model_desc/comment_desc.ml
src/parser/semantics.ml
test/compile/cases/parser_errors.mli
test/compile/expect/parser_errors.txt
test/parser/expect/raw-markup/incorrect-case-target.txt
test/parser/expect/raw-markup/invalid-target.txt
test/parser/test.ml
test/print/print.ml

With this change, the frontend of odoc doesn't know anything about raw markups anymore. Raw markup is just a pair of a tag designating the language, and some .... raw markup. Each backend will look at the tag and decide for itself what to do with it.
Later on, we can have more sophisticated handling (like HTML backend handling latex raw markup through mathjax, for instance).
So far, the following tags are handled:
- Html backend handles `html` tag
- Latex backend handles `latex` and `tex` tags
- manpage backend handles `manpage`,`roff` and `troff` tags.

Simplify/clarify the handling of raw markup and add support in manpages.

---

src/xref2/env.ml
test/cases/labels.mli
test/html/expect/test_package+ml/Labels/index.html
test/html/expect/test_package+re/Labels/index.html

Fix https://github.com/ocaml/odoc/issues/465
In the example in the issue, `{!LA}` now resolves but `{!t.LA}` don't.

Check comments attached to constructors and fields

---

src/xref2/find.ml
src/xref2/find.mli
src/xref2/ref_tools.ml
src/xref2/tools.ml
src/xref2/tools.mli
test/xref2/subst/test.md

This is on top of https://github.com/ocaml/odoc/pull/445
I think names shouldn't be created outside of `Lang`.
Some are still remaining and could be removed with some work. (eg. constructors, fields and extension constructors don't have names in `Lang`)

xref2: Remove some Name.of_string

---

src/document/ML.ml
src/document/generator.ml
src/document/generator_signatures.ml
src/document/reason.ml
test/cases/functor.mli
test/html/expect/test_package+ml/Functor/index.html
test/html/expect/test_package+ml/Nested/F/index.html
test/html/expect/test_package+ml/Nested/index.html
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+re/Nested/F/index.html
test/man/expect/test_package+ml/Functor.3o
test/man/expect/test_package+ml/Functor.F1.3o
test/man/expect/test_package+ml/Functor.F2.3o
test/man/expect/test_package+ml/Functor.F3.3o
test/man/expect/test_package+ml/Functor.F4.3o
test/man/expect/test_package+ml/Nested.3o
test/man/expect/test_package+ml/Nested.F.3o
test/man/expect/test_package+ml/Recent.3o
test/man/expect/test_package+ml/Recent_impl.3o

The output of functor in odoc is not terribly satisfying. A while ago, I moved the description of parameters to the header of the page, but that didn't make anything better, on the contrary. With the last few changes, we can improve things a little bit more.
This patch sets provides 2 improvements:
- Parameters are back inside the body of the page, inside a (single) header of level 1 (just below the main title). The `Signature` header is gone. As a result, parameters and their documentation are now in the sidebar outline.
- The output of functor declaration uses the short form when available. This applies to all backends and should preserve expansion/alternatives/etc.

Small set of patches for functors

---

.github/workflows/build.yml

This adds CI jobs for what OCaml-CI can't do:
- Build and test on Windows and MacOS
- Build with esy
There is still a small hack to install the dependencies of Mdx but it is easy to remove once we fix the root cause.
This should be enough to replace all of our travis script.

Add GitHub actions for building and testing

---

src/odoc/etc/odoc.css

Fix record fields and constructors indentation

---

src/latex/generator.ml

It seems that Latex uses forward slash as file separator on every platforms. Source: https://en.wikibooks.org/wiki/LaTeX/Modular_Documents#Using_different_paths
This is interesting for running the same testsuite on every platforms.

Latex uses forward slash for paths on Windows

---

.gitignore
Makefile

`make -j duniverse` assembles the basic dependencies of odoc in the tree (including dune) and further invocations will use this duniverse.
Not all the targets work, since Dune's `@` targets propogate a bit too readily.
Ultimately, being able to compile the odoc binary with its dependencies is useful in the OCaml (manual) tree - but I'm parking this here for now in case its useful, and because odoc doesn't build with OCaml trunk at the moment.

Add duniverse target

---

Makefile
odoc.opam
src/document/dune
src/html/dune
src/latex/dune
src/manpage/dune
src/model/dune
src/model_desc/dune
src/odoc/bin/dune
src/odoc/dune
src/parser/dune
src/xref2/dune

We can now use the instrumentation feature from Dune 2.7.0 and remove the use of `Jbuild_plugin`.
We already depend on Dune 2.7.0, I just added the missing constraint.

Upgrade bisect 250

---

.github/workflows/build.yml

Coveralls will keep our coverage stats and shows us how they evolve after each PRs.

CI: Send coverage to Coveralls

---

src/latex/generator.ml
src/latex/raw.ml
src/latex/raw.mli
test/latex/expect/test_package+ml/Recent.tex
test/latex/expect/test_package+ml/Recent_impl.B.tex
test/latex/expect/test_package+ml/Recent_impl.tex
test/latex/expect/test_package+ml/Type.tex
test/latex/expect/visualizer.tex

While compiling the OCaml manual, it may happen (or not) that very large sum types make the hyperref package self-destruct with 
> \pdfendlink ended up in different nesting level than \pdfstartlink
due to a bad interaction between the hyperref and longtable package.
There is no clear fix beyond manual edition of the source, which is not reasonable for the generated latex source.
Thus this PR simply limits the number of rows of generated tables, which in turns removes the assumption that there is a reasonable latex package that knows how to handle multi-pages tables.

latex backend: avoid hyperref and longtable destructive interferences

---

src/xref2/ref_tools.ml
test/xref2/refs/refs.md

Fixes https://github.com/ocaml/odoc/issues/523
References with explicit `type:` or `type-` would not resolve classes or class types (except in one case).
This brings a new inconsistency: `type-cl.method-m` is not a valid reference due to the type of method references. Should we relax this or is it expected ? (classes are types but types are not classes)

 Allow type references to resolve to classes 

---

src/xref2/errors.ml
src/xref2/expand_tools.ml
src/xref2/tools.ml
src/xref2/type_of.ml

The code for 'module type of' expansion runs before any other resolution
happens, and it needs to run until a fixed point. Since the change to
use 'Result.t' over simply raising exceptions when we notice we'll need
to recurse, a bug was introduced when the specific error case we're
looking for was swallowed in another layer. This PR attempts to make
sure we don't ever throw away an error raised during signature expansion
and adds some code to check in the combined error whether the root cause
was in fact the case we're looking for; `` `UnexpandedTypeOf `` in this
case.

Better handling of errors in 'type_of.ml'

---

src/document/doctree.ml
src/model_desc/comment_desc.mli
src/model_desc/lang_desc.ml
src/model_desc/paths_desc.ml
src/model_desc/paths_desc.mli
src/odoc/bin/main.ml
src/odoc/rendering.ml
src/odoc/rendering.mli
src/xref2/compile.ml
src/xref2/errors.ml
src/xref2/type_of.ml
src/xref2/type_of.mli
test/xref2/lib/common.cppo.ml

This commit prevents the accidental inclusion of paths that refer to
hidden modules. Usually the cause of this is there is no mli file for
the module and that the inferred types go directly to the type in the
hidden module without going via the module that declares the canonical
paths, so it's as if you've directly referred to a module with a `__` in
its name. The best fix for this is to write an mli file, and the second
best fix is to use some type annotations. This is occasionally tricky
where polymorphic variants are in play.

Fix some leaking hidden paths

---

src/loader/cmi.ml
src/loader/cmt.ml
src/loader/cmti.ml

Previously this was displayed as a prefix operator, but the bitwise negation operator `lnot` is [implemented as a function](https://github.com/ocaml/ocaml/blob/4.12/stdlib/stdlib.mli#L413) and the OCaml parser [does not provide a special-case](https://github.com/ocaml/ocaml/blob/4.12/parsing/lexer.mll#L92-L98) for it.

Avoid parenthesising the function `lnot`

---

src/xref2/compile.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/find.ml
src/xref2/find.mli
src/xref2/link.ml
src/xref2/subst.ml
src/xref2/subst.mli
src/xref2/tools.ml
test/xref2/strengthen/test.md
test/xref2/subst/dune
test/xref2/subst/test.md

Fix https://github.com/ocaml/odoc/issues/538 and https://github.com/ocaml/odoc/issues/462
This substitutes recursively type variables when encountering a "replaced" type.

Fix substitution of type params

---

.github/workflows/build.yml
odoc.opam
src/xref2/errors.ml
test/parser/dune
test/print/dune

OCaml-CI doesn't test below 4.04.1.
Parser tests are disabled below 4.04.1 because `sexplib0` is not available.

Enable CI for OCaml 4.02.3

---

src/odoc/etc/odoc.css

This PR addresses issue #425
**_Before:_**
**_After:_**

improve readabilty for linkables in dark mode

---

src/document/generator.ml
test/html/expect/test_package+ml/Class/index.html
test/html/expect/test_package+ml/Labels/index.html
test/html/expect/test_package+re/Class/index.html
test/html/expect/test_package+re/Labels/index.html

The rendering looked like that before:
`class type ctobject ... end`
After:
`class type ct = object ... end`

Generator: Fix missing '=' after 'class type'

---

src/document/generator.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml

Resolved fragments pointing to hidden paths were causing broken links. This PR fixes that.

Hidden fragment fixes

---

src/html/generator.ml
src/html/generator.mli
src/html/tree.ml
src/html/tree.mli
src/odoc/bin/main.ml
src/odoc/html_page.ml
src/odoc/html_page.mli
src/xref2/compile.ml
src/xref2/env.ml
src/xref2/link.ml

Add a parameter to `html-generate` to format the output nicely - useful for diffing
Also this no longer causes exceptions when processing 'packed' compilation units.

Html indent

---

src/odoc/bin/main.ml
src/odoc/rendering.ml
src/odoc/rendering.mli

For backward compatibility, `odoc html-targets` can work on odoc files
as well as odocl files. When working on odoc files, it does the link
step (without writing the odocl file) then proceeds as usual on the
result. This is obviously inefficient, but the result is accurate.

Fix `html-targets` when operating on odoc files

---

src/odoc/interface.mld

Add interface doc

---

src/model_desc/comment_desc.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/link.ml
test/pages/resolution.t/run.t
test/xref2/cross_references.t/run.t
test/xref2/references_scope.t/a.mli
test/xref2/references_scope.t/run.t

This fixes https://github.com/ocaml/odoc/issues/585 but doesn't fix the issue reported by this comment https://github.com/ocaml/odoc/issues/585#issuecomment-777599121
Resolution failed because doc comment of a file was resolved before the rest of the module is added to the environment.
The first commit is unrelated, it removes the location from `odoc_print`'s output to make the output more readable.
The second issue seems to be in the loader, I'm still investigating.

Fix unresolved references from the first comment of a file

---

src/document/comment.ml
src/model/comment.ml
src/model_desc/comment_desc.ml
src/parser/semantics.ml
src/xref2/link.ml
test/html/expect/test_package+ml/Markup/index.html
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+re/Markup/index.html
test/html/expect/test_package+re/Ocamlary/index.html
test/latex/expect/test_package+ml/Markup.tex
test/man/expect/test_package+ml/Markup.3o
test/print/print.ml
test/xref2/module_list.t/external.mli
test/xref2/module_list.t/main.mli
test/xref2/module_list.t/run.t

Fixes https://github.com/ocaml/odoc/issues/297
Resolve and render the synopsis of modules referenced with the `{!modules:A B C}` markup.
The first sentence of the first paragraph of the modules' documentation is taken. Headings, tags and other elements that are not paragraphs and lists are skipped, I think that's what ocamldoc does: https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sss:ocamldoc-preamble

Render modules synopsis for `{!modules:...}`

---

src/loader/odoc_loader.ml
src/model/lang.ml
src/odoc/compile.ml
src/odoc/html_fragment.ml
src/xref2/link.ml
test/xref2/lib/common.cppo.ml

To ensures that linking is not done twice. This can happen when inadvertently using the `html` command instead of
`html-generate`.
Some elements can't be linked twice and will cause an exception. For example when linking `{!modules:...}`.

Add the 'linked' flag to compilation units

---

Makefile
src/xref2/compile.ml
src/xref2/link.ml
test/cases/toplevel_comments.mli
test/html/expect/test_package+ml/Toplevel_comments/Include_inline'/index.html
test/html/expect/test_package+ml/Toplevel_comments/Include_inline/index.html
test/html/expect/test_package+ml/Toplevel_comments/index.html
test/html/expect/test_package+ml/Toplevel_comments/module-type-Include_inline_T'/index.html
test/html/expect/test_package+ml/Toplevel_comments/module-type-Include_inline_T/index.html
test/html/expect/test_package+ml/Toplevel_comments/module-type-T/index.html
test/html/expect/test_package+re/Toplevel_comments/Include_inline'/index.html
test/html/expect/test_package+re/Toplevel_comments/Include_inline/index.html
test/html/expect/test_package+re/Toplevel_comments/index.html
test/html/expect/test_package+re/Toplevel_comments/module-type-Include_inline_T'/index.html
test/html/expect/test_package+re/Toplevel_comments/module-type-Include_inline_T/index.html
test/html/expect/test_package+re/Toplevel_comments/module-type-T/index.html
test/html/test.ml
test/html/tidy.ml

Fixes the initial issue of https://github.com/ocaml/odoc/issues/478 but doesn't implement @lpw25's suggestion.
The first doc-comment of the expansion of an include was always removed. This PR avoids this for `@inline` includes.
The first two commits are unrelated.

Don't remove the doc of inline includes

---

src/compat/odoc_compat.ml
src/document/generator.ml
src/loader/cmi.ml
src/loader/cmi.mli
src/loader/cmt.ml
src/loader/cmti.ml
src/loader/cmti.mli
src/loader/doc_attr.ml
src/loader/doc_attr.mli
src/loader/dune
src/loader/ident_env.cppo.ml
src/loader/ident_env.cppo.mli
src/model/dune
test/cases/stop_dead_link_doc.mli
test/html/expect/test_package+ml/Stop_dead_link_doc/index.html
test/html/expect/test_package+re/Stop_dead_link_doc/index.html
test/html/test.ml

Stop rendering dead links

---

src/latex/raw.ml
test/latex/expect/test_package+ml/Markup.tex

The addition of synopsis to module list generated by `{!modules}` broke the latex manual by putting complex elements (inlined code block with links) in the label part of description items. The compilation of odoc latex text was also broken, due to an empty `{!modules:}`.
This PR fixes boths issue by hardening the description environment:
- empty descriptions are no longer printed
-  the label of description items are rendered inside a latex group (`{}`)

latex backend: harden description environment

---

src/loader/doc_attr.ml
test/xref2/module_list.t/external.mli
test/xref2/module_list.t/main.mli
test/xref2/module_list.t/run.t
test/xref2/module_list.t/starts_with_open.mli

Finally closes https://github.com/ocaml/odoc/issues/328
Odoc doesn't render `open`s so it makes sense to expect the top-comment to be placed after.

Skip opens when looking up the top-comment

---

src/html/generator.ml
src/odoc/etc/odoc.css
test/html/expect/test_package+custom_theme,ml/Include/index.html
test/html/expect/test_package+ml/Include/index.html
test/html/expect/test_package+ml/Include2/index.html
test/html/expect/test_package+ml/Include_sections/index.html
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+ml/Toplevel_comments/Include_inline'/index.html
test/html/expect/test_package+ml/Toplevel_comments/Include_inline/index.html
test/html/expect/test_package+ml/Toplevel_comments/module-type-Include_inline_T'/index.html
test/html/expect/test_package+ml/Toplevel_comments/module-type-Include_inline_T/index.html
test/html/expect/test_package+re/Include/index.html
test/html/expect/test_package+re/Include2/index.html
test/html/expect/test_package+re/Include_sections/index.html
test/html/expect/test_package+re/Ocamlary/index.html
test/html/expect/test_package+re/Toplevel_comments/Include_inline'/index.html
test/html/expect/test_package+re/Toplevel_comments/Include_inline/index.html
test/html/expect/test_package+re/Toplevel_comments/module-type-Include_inline_T'/index.html
test/html/expect/test_package+re/Toplevel_comments/module-type-Include_inline_T/index.html

This PR is build on top of #607 the relevant commits are the 4 last ones (sorry for always proceeding that way but changing the markup bit-by-bit in different branches is too unconvenient).
The current structure of includes is quite involved and messy. For one non-inlined include we have:
```
div.odoc-include
div."spec include"
div.doc 
content of doc string (may be multiple paragraphs)
details 
summary
span.def
code
include defs
```
This PR proposes to change the structure to 
```
div.odoc-include 
div.spec-doc
content of doc string
details
summary."spec include"
code
include defs
```
Except for the docstring of the include coming *before* the specification (it would have been nice to put in the `summary`, but the content model  disallows it). This more regular with other structure items …

Refine includes

---

src/model/reference.ml
test/parser/expect/reference-component-kind/dash-in-page-name.txt
test/parser/expect/reference-component-kind/dot-and-dash-in-page-name.txt
test/parser/expect/reference-component-kind/kind-with-quotes.txt
test/parser/expect/reference-component-kind/no-kind-with-quotes.txt
test/parser/expect/reference-component-kind/reference-with-unmatched-quotation.txt
test/parser/test.ml

Fixes https://github.com/ocaml/odoc/issues/590

Tweak syntax for page name refs

---

src/document/ML.ml
src/document/generator.ml
src/document/generator_signatures.ml
src/document/reason.ml
src/document/types.ml
src/html/generator.ml
src/latex/generator.ml
src/odoc/etc/odoc.css
test/html/expect/test_package+ml/Labels/index.html
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+ml/Recent/index.html
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Labels/index.html
test/html/expect/test_package+re/Ocamlary/index.html
test/html/expect/test_package+re/Recent/index.html
test/html/expect/test_package+re/Type/index.html

This is an alternative take on the copy paste problem mentioned in https://github.com/ocaml/odoc/issues/296. It inserts comment delimiters (in ocaml, `(*` `*)`) around documentation, but hide them while keeping them in the text selection with some CSS trickery. The trickery in question seems rather standard (it's used in bootstrap as a way to have text only for screen-readers, which is rather consistent with what we want). It also has the advantage that people can style it to keep the delimiters in their own CSS, if they like that.
cc @dbuenzli

Make type definition copy-pastable with hidden comment delimiters.

---

.git-blame-ignore-revs
.ocp-indent

This only fixes the most annoying case: match clauses.
Ocp-indent doesn't offer enough options to fix this problem entirely (and that's fine because we shouldn't think about formatting now because of OCamlformat).
A lot of things are still not right: indentation inside a `(fun ...)`, long type constraints on `let`, etc..

Tweak ocp-indent config

---

src/document/generator.ml
src/latex/generator.ml
src/manpage/generator.ml
test/html/expect/test_package+ml/Bugs/index.html
test/html/expect/test_package+ml/Bugs_pre_410/index.html
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+ml/Type/index.html
test/html/expect/test_package+re/Bugs/index.html
test/html/expect/test_package+re/Bugs_pre_410/index.html
test/html/expect/test_package+re/Ocamlary/index.html
test/html/expect/test_package+re/Type/index.html

It breaks cut and paste in the HTML renderer and other renderers have to ignore it.
Closes #620.

IR model: stop trying to play with word joiners (U+2060)

---

src/document/comment.ml
src/document/generator.ml
src/document/utils.ml
test/html/expect/test_package+ml/Labels/index.html
test/html/expect/test_package+ml/Nested/F/argument-1-Arg1/index.html
test/html/expect/test_package+ml/Nested/F/argument-2-Arg2/index.html
test/html/expect/test_package+ml/Nested/F/index.html
test/html/expect/test_package+ml/Nested/X/index.html
test/html/expect/test_package+ml/Nested/module-type-Y/index.html
test/html/expect/test_package+re/Labels/index.html
test/html/expect/test_package+re/Nested/F/argument-1-Arg1/index.html
test/html/expect/test_package+re/Nested/F/argument-2-Arg2/index.html
test/html/expect/test_package+re/Nested/F/index.html
test/html/expect/test_package+re/Nested/X/index.html
test/html/expect/test_package+re/Nested/module-type-Y/index.html
test/latex/expect/test_package+ml/Nested.F.tex
test/latex/expect/test_package+ml/Nested.tex
test/man/expect/test_package+ml/Nested.3o
test/man/expect/test_package+ml/Nested.F.3o
test/man/expect/test_package+ml/Nested.X.3o
test/xref2/module_preamble.t/b.mli
test/xref2/module_preamble.t/run.t

Closes https://github.com/ocaml/odoc/issues/235 and https://github.com/ocaml/odoc/issues/631
If the preamble contains a level 1 heading, this heading and the rest of the preamble is moved out of the 'header' to the 'content' of the page.
That part of the preamble is rendered after the TOC and appears in it.
Heading of level 2 or higher are kept in the preamble.
cc @Drup, @dbuenzli

Cut the preamble at the first top-level heading

---

src/document/comment.ml
src/document/generator.ml
src/model/comment.ml
src/odoc/interface.mld
src/xref2/link.ml
test/html/expect/test_package+ml/Ocamlary/index.html
test/html/expect/test_package+ml/Toplevel_comments/index.html
test/html/expect/test_package+re/Ocamlary/index.html
test/html/expect/test_package+re/Toplevel_comments/index.html
test/xref2/module_preamble.t/run.t

Fixes https://github.com/ocaml/odoc/issues/632
Before this patch, no synopsis was attached to declarations like this: (also work on classes, class types and module types)
```ocaml
module M : sig
(** Expansion doc. *)
end
```
This is consistent with what ocamldoc does.
The first commit refactors the function generating the synopsis for `{!modules:}` lists so it can be shared with the generator. Before that, a simpler rule was used that didn't skip headings and other elements:
```ocaml
(** {1 Heading}
@canonical M
This is the synopsis. *)
```
```ocaml
(** - This is the synopsis. *)
```
These are rules I made up in https://github.com/ocaml/odoc/pull/597, it's still time to change them and to document them too.

Take expansion's doc when computing a declaration's synopsis

---

src/odoc/using-odoc.mld

The `preamble` and `synopsis` parts describe the current state of https://github.com/ocaml/odoc/pull/640 and https://github.com/ocaml/odoc/pull/643

Document how to write documentation for modules

---

.ocamlformat-ignore
src/loader/doc_attr.mli
src/loader/odoc_loader.ml
src/loader/odoc_loader.mli
src/model/lang.ml
src/model_desc/lang_desc.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/ref_tools.ml
src/xref2/tools.ml
test/xref2/canonical_unit.t/run.t
test/xref2/canonical_unit.t/test.ml
test/xref2/canonical_unit.t/test__x.mli
test/xref2/lib/common.cppo.ml

Fix https://github.com/ocaml/odoc/issues/559#event-4382610148
Before this, `@canonical` tags in the top-comments of a file were ignored.

Handle @canonical tags on compilation unit

---

src/odoc/etc/odoc.css

While trying the latest version of Odoc (to test with destructive substitution) I noticed that, on Firefox, some colours were not displayed.
According to https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties, you can directly describe a fallback in the accessor of a variable (and this had already been used for a rule).
After this modification, the output is the same of 1.5.2.

Add some missing variables in light-theme

---

src/document/generator.ml
src/model/lang.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/link.ml
test/html/expect/test_package+ml/Toplevel_comments/Include_inline/index.html
test/html/expect/test_package+ml/Toplevel_comments/index.html
test/html/expect/test_package+ml/Toplevel_comments/module-type-Include_inline_T/index.html
test/html/expect/test_package+re/Toplevel_comments/Include_inline/index.html
test/html/expect/test_package+re/Toplevel_comments/index.html
test/html/expect/test_package+re/Toplevel_comments/module-type-Include_inline_T/index.html
test/xref2/module_list.t/run.t

Finally closes https://github.com/ocaml/odoc/issues/478 (this is the last remaining issue).
A signature starting with an `include` with the `@inline` tag that doesn't have a top-comment inherits the top-comment from the included module type.
On top of https://github.com/ocaml/odoc/pull/647. It's changing unrelated code but the expanded documentation would be rendered twice otherwise.

Inherit top-comment from @inline includes 

---

src/model/paths.ml

Without this I get a warning and runtime error from js_of_ocaml
complaining about the missing primitive `caml_alloc_dummy_infix`. Not
quite sure what this nor why this patch fixes it!

Fix js_of_ocaml compilation

---

src/xref2/env.ml
src/xref2/env.mli
src/xref2/ref_tools.ml
test/xref2/references_scope.t/run.t
test/xref2/references_scope.t/shadowed.mli
test/xref2/references_scope.t/shadowed_through_open.mli
test/xref2/v407_and_above/labels.t/run.t
test/xref2/v408_and_above/github_issue_587.t/run.t

Fixes https://github.com/ocaml/odoc/issues/648
This PR implements shadowing when resolving submodules. Before, several items with the same name were added to the environment, which caused the warnings.
The notion of scope didn't change: the whole signature is added to the environment before any reference is resolved (including opens and includes).

Fix references to shadowed items

---

src/html/generator.ml
src/loader/cmi.ml
src/loader/cmt.ml
src/loader/cmti.ml
src/loader/ident_env.cppo.ml
src/xref2/env.ml
test/xref2/lib/common.cppo.ml

This PR makes odoc build on OCaml 4.13 but does not handle the new `with module type` feature.
This PR mostly adapts the loaders code to the few ASTs change in 4.13 .
There are also few fixed related to the change of typing for `|>`.

Minimal 4.13 support

---

src/loader/cmi.ml
src/loader/cmt.ml
src/loader/cmti.ml
src/model/ident_env.cppo.ml

Cherry-picked from the 2.0 version, with a failure message which mentions that the new 4.13 features are only supported by odoc 2.0 and later.

Minimal 4.13 support for 1.5 branch

---

src/xref2/errors.ml
src/xref2/lookup_failures.ml
src/xref2/lookup_failures.mli
src/xref2/ref_tools.ml
test/xref2/resolve/test.md
test/xref2/warnings.t/run.t

Fixes https://github.com/ocaml/odoc/issues/635
These errors are common and are usually repeated several time. With this commit, they are merged into one message with only the necessary informations:
```
File "<test>":
Couldn't find the following modules:
Stdlib
```
I initially tried to handle these errors while resolving imports but it was showing mangled names (eg. `Stdlib__bytes Stdlib__string ...` instead of `Stdlib`) and unused modules (eg. `CamlinternalFormatBasics`) and decreased performances a bit.

Aggregate "root" lookup failures

---

test/generators/gen_rules/gen_rules.ml
test/generators/gen_rules_lib.ml
test/generators/link.dune.inc

The first commit fixes an error due to Dune generating a `.formatted` directory:
```
gen_rules test/generators/link.dune.inc.gen (exit 1)
(cd _build/default/test/generators && gen_rules/gen_rules.exe) > /run/user/1000/build5576de.dune/dune-pipe-action-c4bd75.stdout
Don't know what to do with 'cases/.formatted' because of unrecognized '' extension.
```
Input paths were handled in several places so I factorized that part of the code with the help of an intermediate type.
The second commit removes the duplication of code related to generating Dune rules with the help of more general functions and fixes some mishandling of paths (eg. related to extensions or conversions to string). 
The diff is huge because the generated dune file changes a lot.

Fix spurious error in generator tests

---

src/xref2/subst.ml
src/xref2/type_of.ml
test/xref2/include_module_type_of.t/run.t
test/xref2/include_module_type_of.t/uwt_base.mli

Two fixes and a test:
1. Slightly more recursion needed when expanding `module type of`
expressions before compilation
2. In the presence of `module type of` expressions and `includes`,
we can get in the situation when we try to rename elements that
have been prefixed. This is not an error, though it is unusual.
we end up labelling the items with different idents, but that's
fine because all expressions referencing them are using the
prefixed path anyway.
The test is a much cut-down version of `uwt` that was originally
demonstrating the problem, manifesting as an internal `Failure`
begin raised.

Fix a bug in subst noticed in `uwt`

---

src/document/comment.ml
test/generators/html/Ocamlary.html
test/generators/latex/Ocamlary.tex
test/generators/man/Ocamlary.3o
test/xref2/v407_and_above/labels.t/run.t

Fixes ocaml/v3.ocaml.org-server#83

Remove the prefix when rendering a label reference

---

src/xref2/errors.ml
src/xref2/link.ml
src/xref2/ref_tools.ml
src/xref2/ref_tools.mli
test/xref2/module_list.t/run.t
test/xref2/references_scope.t/run.t
test/xref2/references_to_pages.t/run.t
test/xref2/refs/refs.md
test/xref2/v407_and_above/labels.t/run.t
test/xref2/warnings.t/run.t

Closes https://github.com/ocaml/odoc/issues/664
Add a warning when a reference failed to resolve. Before, this was not reported at all.

Report failures when resolving references

---

src/document/generator.ml
src/xref2/compile.ml
src/xref2/test.md
src/xref2/tools.ml
test/xref2/deep_substitution.t/m.mli
test/xref2/deep_substitution.t/run.t
test/xref2/with.t/run.t

Fixes #690
There has been logic to fix this sort of issue for a long time, but it
broke at some point.
Mostly the fix is that when calculating the signatures of `With`
module expressions, we always recalculate rather than using any
previously calculated signature - this is because the previously
calculated signature makes a round-trip from Component.* to Lang.* and
Lang.ModuleType.simple_signature doesn't preserve removed items as the
Components layer does.
By itself this would not have fixed #690 though - The way the rest of
the fix works is by ensuring that at each level of the expansion we
have enough to figure out that a replacement is necessary and what it
should be. For example, in issue #690, @Octachron provides the
following example:
```ocaml
module type S = sig
module M: sig
type …
```

Fix resolution involving deeply nested substitutions

---

src/xref2/compile.ml
src/xref2/paths.md
test/xref2/resolve/test.md

It's quite reasonable for a module to have no expansion.

OpaqueModule is not necessarily an error

---

src/loader/odoc_loader.ml
test/integration/compile.t/line_numbers.mld
test/integration/compile.t/run.t

**warning:** not extensively tested. if others could also test that'd be great.
please let me know if i need to add regression tests (or anything else)
it's a very small and simple change so just committing to master and closing this also works

fix line number off-by-one-error

---

src/document/comment.ml
src/model/comment.ml
src/model/semantics.ml
src/model_desc/comment_desc.ml
test/model/semantics/test.ml

In the next version of 'odoc-parser', the representation of code blocks
changes. We can make Odoc work with both versions easily.
With this change, Odoc will be compatible with the current and next versions of Mdx and OCamlformat.

Stay compatible with two versions of the parser

---

src/loader/cmt.ml
src/loader/cmti.ml
src/loader/doc_attr.ml
src/loader/doc_attr.mli
test/generators/html/Nested-F.html
test/generators/html/Ocamlary.html
test/generators/html/highlight.pack.js
test/generators/html/odoc.css
test/generators/latex/Nested.F.tex
test/generators/latex/Ocamlary.tex
test/generators/man/Nested.F.3o
test/generators/man/Ocamlary.3o
test/xref2/ambiguous_label.t/run.t
test/xref2/labels.t/run.t
test/xref2/refs/refs.md

This PR splits the first comment in a signature at the firstheading. This means everything before will be put into the preamble of the page, and the rest of the comment becomes part of the signature. Since the top comment has never been put into the environment, previously this meant that the labels couldn't be referenced. Now they are part of the signature this starts to work.
Fixes #740

Allow referencing labels in the top comment

---

doc/odoc_for_authors.mld

There was some previous documentation but it was hidden in the List markup section, so well hidden I didn't even know it existed before working on this PR.
This adds a specific section for code blocks, split into sub section for each type of blocks with a bit more detailed documentation on how they are formatted and actual examples for the exact syntax.
It also adds documentation on the recently added language headers.
Some of the examples in this section had to be written in verbatim blocks because of the bug reported in #776.

Add extensive documentation for code fragments markup

---

src/loader/cmi.ml
src/loader/cmi.mli
src/loader/cmt.ml
src/loader/cmti.ml
src/model/error.ml
src/model/lang.ml
src/model/location_.ml
src/model/location_.mli
src/xref2/component.ml
src/xref2/component.mli
src/xref2/lang_of.ml
src/xref2/link.ml
src/xref2/lookup_failures.ml
src/xref2/lookup_failures.mli
test/pages/errors.t/run.t
test/xref2/labels/ambiguous_label.t/run.t
test/xref2/labels/ambiguous_label_warning.t/run.t
test/xref2/labels/labels.t/run.t
test/xref2/module_list.t/run.t
test/xref2/multi_file_module_type_of.t/run.t
test/xref2/references_scope.t/run.t
test/xref2/references_to_pages.t/run.t
test/xref2/refs/refs.md
test/xref2/unexpanded_module_type_of.t/run.t
test/xref2/warnings.t/run.t

Re-open of https://github.com/ocaml/odoc/pull/762, which can't be re-opened after a force-push, it seems.

Add context around errors from expansion of includes

---

src/xref2/env.ml
src/xref2/ref_tools.ml
test/xref2/labels/ambiguous_label.t/run.t
test/xref2/labels/ambiguous_label_warning.t/run.t
test/xref2/labels/ambiguous_label_warning.t/test.mli
test/xref2/labels/labels.t/run.t

We already warn when defining an explicit label that conflicts with another,
but this PR adds a warning when trying to reference a label that is ambiguous.

Warn on reference to ambiguous label

---

src/model/error.ml
src/xref2/lookup_failures.ml
test/integration/compile.t/run.t
test/model/internal_tags.t/run.t
test/xref2/labels/ambiguous_label.t/run.t
test/xref2/labels/ambiguous_label_warning.t/run.t
test/xref2/labels/labels.t/run.t
test/xref2/module_preamble.t/run.t
test/xref2/ocaml_stdlib.t/run.t
test/xref2/refs/refs.md
test/xref2/unexpanded_module_type_of.t/run.t
test/xref2/warnings.t/run.t

The prefix was incorrectly computed and was always "Error" for a class of warnings and "Warning" for others.
Now, correctly take into account the warn-error option.

Fix the warning/error prefix

---

CHANGES.md
src/xref2/compile.ml
test/generators/html/Module_type_alias-module-type-E-argument-2-C.html
test/generators/html/Module_type_alias-module-type-E.html
test/generators/html/module_type_alias.targets
test/generators/latex/Module_type_alias.tex
test/generators/link.dune.inc
test/xref2/resolve/test.md

This was causing the module_type_alias test to produce a functor expansion with two arguments labelled '1'.

Fix error in xref

---

CHANGES.md
src/document/generator.ml
src/loader/cmt.ml
src/loader/cmti.ml
src/model/lang.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/env.ml
src/xref2/lang_of.ml
src/xref2/link.ml
src/xref2/subst.ml
test/generators/cases/toplevel_comments.mli
test/generators/html/Toplevel_comments-Comments_on_open-M.html
test/generators/html/Toplevel_comments-Comments_on_open.html
test/generators/html/Toplevel_comments.html
test/generators/html/toplevel_comments.targets
test/generators/latex/Toplevel_comments.tex
test/generators/link.dune.inc
test/generators/man/Toplevel_comments.3o
test/generators/man/Toplevel_comments.Comments_on_open.3o
test/generators/man/Toplevel_comments.Comments_on_open.M.3o
test/generators/man/toplevel_comments.targets

This PR fixes #745 by keeping comments attached to open.
They are handled the same way as floating comments.

Do not drop comments attached to open

---

src/loader/cmt.ml
src/loader/cmti.ml

This PR fixes #745 for versions of ocaml older than 4.08. It solves the failure of tests introduced in #797 for those versions.

Fix tests for old versions of ocaml (<4.08)

---

src/html/generator.ml
src/odoc/etc/odoc.css
test/generators/html/Include-module-type-Dorminant_Module.html
test/generators/html/Include.html
test/generators/html/Ocamlary-module-type-C.html
test/generators/html/Ocamlary-module-type-IncludeModuleType.html

This PR propose a fix of #725.
It adds a class `"shadowed-include"` to the html element containing an empty include.
This way, it is easy to change how these elements are displayed without changing odoc itself, just adding css.
By default, in this PR, it is not displayed.
However, the first suggestion of @asavahista on #725, of having a special formatting for these, could be implemented as well.

Add a class and a css rule for empty includes

---

odoc.opam

This was added when we had a circular dependency because odoc-parser
was part of odoc.

Loosen hard version dependency added as a workaround

---

src/xref2/compile.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/link.ml
test/xref2/dune
test/xref2/github_issue_793.t/irmin_layers_intf.ml
test/xref2/github_issue_793.t/run.t
test/xref2/refs/refs.md

The scope of the substitutions shouldn't escape the signature. So
the substitutions are only added to the environment explicitly during
the compile/link processing of signatures, not in the more general
'Env.open_signature'. Included in this commit is a test for GH issue
793 which was a manifestation of the problem this caused.

Better handling of substitutions

---

CHANGES.md
doc/odoc_for_authors.mld
src/loader/doc_attr.ml

Currently, odoc fails to extract synopsis from a signature pre-processed by a ppx. This is because ppx add a "ocaml.ppx.context" attribute at top level before the top comment.
I'm not sure the current fix is the best way to fix, since it uses string matching "ocaml.text" to continue unrolling the list of items until it finds an attribute that is a document.

Ignore non doc attributes at top level genrated by ppx

---

src/odoc/etc/odoc.css

A small style fix: Make sure that the content is more obviously associated with the correct signature item.
Before:
After:

Adjust spacing between spec items

---

.ocamlformat-ignore
src/compat/compatcmdliner.ml
src/compat/dune
src/odoc/bin/dune
src/odoc/bin/main.ml
test/odoc_print/dune
test/odoc_print/odoc_print.ml

Unfortunately cmdliner 1.1.0 is 4.08 and upwards only, and since odoc
supports OCaml 4.02.3 we have to stay on the old API. This commit introduces
a stub library that re-exposes the deprecated interface, supressing the
deprecation notices.

Cmdliner 1.1.0 compatibility take 2

---

test/integration/simple_dune_project.t/run.t

Dune 3.0 doesn't build docs for hidden modules.

Dune 3.0 compatibility

---

src/document/comment.ml
src/loader/cmi.ml
src/loader/cmi.mli
src/loader/cmt.ml
src/loader/cmti.ml
src/loader/doc_attr.ml
src/loader/doc_attr.mli
src/loader/ident_env.cppo.ml
src/model/comment.ml
src/model/semantics.ml
src/model/semantics.mli
src/model_desc/comment_desc.ml
test/generators/cases/alerts.mli
test/generators/html/Alerts-Top1.html
test/generators/html/Alerts-Top2.html
test/generators/html/Alerts.html
test/generators/html/alerts.targets
test/generators/latex/Alerts.tex
test/generators/latex/alerts.targets
test/generators/link.dune.inc
test/generators/man/Alerts.3o
test/generators/man/Alerts.Top1.3o
test/generators/man/Alerts.Top2.3o
test/generators/man/alerts.targets

This PR lifts `deprecated` and [alerts](https://ocaml.org/manual/alerts.html) into `odoc` tags.
`[@@deprecated]` and `[@@alert deprecated]` are handled internally the same way. and rendered similarly to the existing `@deprecated` odoc tag. Alerts are rendered as `alert alert_name` followed by the possible payload.
When an item contains both a `deprecated` attribute and an attached comment with a `deprecated` `odoc` tag, only the `odoc` tag is kept. This allows to use references in `@deprecated` message, as payloads from alerts or attribute are not parsed by odoc.
This PR closes #406

Lift `deprecated` and `alerts` attributes into odoc tags

---

src/loader/doc_attr.ml
test/generators/cases/stop.mli
test/generators/cases/stop_first_comment.mli
test/generators/html/Stop-O.html
test/generators/html/Stop-P.html
test/generators/html/Stop.html
test/generators/html/Stop_first_comment.html
test/generators/html/stop.targets
test/generators/html/stop_first_comment.targets
test/generators/latex/Stop.tex
test/generators/latex/Stop_first_comment.tex
test/generators/latex/stop_first_comment.targets
test/generators/link.dune.inc
test/generators/man/Stop.3o
test/generators/man/Stop.O.3o
test/generators/man/Stop.P.3o
test/generators/man/Stop_first_comment.3o
test/generators/man/stop.targets
test/generators/man/stop_first_comment.targets

The commit ae62263a914d fixed the handling of stop-comments when it is at the beginning of a signature. For example, it's no longer needed to add an empty comment in https://github.com/dbuenzli/affect/blob/815b99ebf9d4f0c2921886fab76d275f982c0340/src/fiber.mli#L121
But it also added a new bug when the stop-comment follows a top-comment. Both `foo` and `bar` were hidden in this example:
```ocaml
(** Top-comment *)
(**/**)
val foo : int
(**/**)
val bar : int
(**/**)
val baz : int
```
This PR fixes that and adds tests.

Fix stop-comment when it follows the top-comment

---

.ocamlformat
src/html/generator.ml

In order to minimise problems with current PRs, this enables the
deprecated 'module-item-spacing=preserve'.

Upgrade to ocamlformat 0.21.0

---

odoc.opam
src/document/codefmt.ml
src/document/comment.ml
src/document/types.ml
src/html/generator.ml
src/latex/generator.ml
src/manpage/generator.ml
src/model/comment.ml
src/model/semantics.ml
src/model_desc/comment_desc.ml
test/model/semantics/test.ml

Pass the language tag through the model and to highlightjs in the html generator. The value is ignored in other backends.
Code blocks with no language specified are rendered as before (highlighted).
Highlightjs should recognize `plain`, `plaintext` and `text` to disable highlighting but perhaps we should have a string specific to Odoc that we can document and handle specifically ?
The version of highlightjs vendored only support one language (OCaml) and is not updated in this PR.

Handle language tag on code blocks

---

src/odoc/etc/odoc.css

This small PR fixes #838.
Here is a screenshot of the new layout on mobile:

Fix body margin on mobile

---

src/odoc/etc/odoc.css

This PR fixes the css introduced in #830:
It find it more logical that odoc comments always have a `--main-background` color, even if they are inside a `spec` (with background `--spec-summary-background`).
I think it makes it easier to read large record fields with many comments attached to fields.
Compare the two images:
with
You can find complete examples of the [old style](https://choum.net/panglesd/parsetree_with_comments_old/html/compilerlibref/Parsetree/index.html) and [new style](https://choum.net/panglesd/parsetree_with_comments/html/compilerlibref/Parsetree/index.html) for this file.
(Maybe the thin blue bar could be removed now that the background is white... what do you think?)

Fix css of layout for datatypes

---

.ocamlformat-ignore
src/document/codefmt.ml
src/document/compat.cppo.ml
src/document/dune

Alternate implementation to #831, retaining the current version matrix.

OCaml 4.02-5.0 support

---

.github/workflows/stale.yml

Monitoring what the bot does is a lot of work.
See for example: https://github.com/ocaml/odoc/issues/574

Stale issue bot: Don't close issues

---

src/model/error.ml
src/model/error.mli
src/odoc/bin/main.ml
src/xref2/lookup_failures.ml
test/xref2/multi_file_module_type_of.t/run.t
test/xref2/unexpanded_module_type_of.t/run.t
test/xref2/warnings.t/run.t

It can be re-enabled via the command-line option
--enable-missing-root-warning
But since this is usually a build system issue rather than something
end-users will need to worry about, let's not complain about it.
Note that this will _not_ suppress warnings generated if references
aren't resolved - so if you explicitly have a reference to something
in a dependency library and it's not found when linking, you'll still
get a warning.
Fixes: #825

Disable the missing root warning by default

---

src/xref2/link.ml
test/generators/cases/tag_link.ml
test/generators/html/Tag_link.html
test/generators/html/tag_link.targets
test/generators/latex/Tag_link.tex
test/generators/latex/tag_link.targets
test/generators/link.dune.inc
test/generators/man/Tag_link.3o
test/generators/man/tag_link.targets

Closes #827.
I noticed that the similar `List` case in `comment_nestable_block_element` uses `List.rev_map ... |> List.rev` instead though. Should it be done here as well?

Add tag content linking

---

src/loader/cmi.ml

Fixes https://github.com/ocaml/odoc/issues/900
This allows to build Odoc with ocaml 5.1.0+trunk as of 2022-10-21.

Compatibility with 5.1.0

---

src/odoc/resolver.ml
test/xref2/github_issue_917.t/foo.mld
test/xref2/github_issue_917.t/foo.mli
test/xref2/github_issue_917.t/run.t

This PR adds prefix "page-" to the target name when adding a page content to the cache.
* In `lookup_page` function, it adds prefix "page-" to the target name when lookup.
* However, when adding a page content to the cache (i.e. `build_env_for_page` -> `build` -> `add_unit_to_cache`), it did not add the prefix.
This discrepancy introduced an incorrect reference resolution when there is the same name of page and module. For example, suppose we have a module `Foo` and a page `Foo.mld` and `Foo.mld` includes a reference to `Foo`, i.e. `{!module-Foo}`.
1. It invokes `build_env_for_page` for the page `Foo.mld`. Now, the cache has a mapping for `Foo`, but its value includes the page content only.
2. When resolving `{!module-Foo}`, it tries to find it from the cache. It found, but the result is …

Add prefix "page-" to target name when adding page content to cache

---

doc/odoc_for_authors.mld

Fix #937:
- Be more consistent with placeholder syntax
- Clarify deprecated reference prefixes
- Clarify heading levels section
- Use non-deprecated `section` instead of `label` in examples.

Clarify "odoc for library authors" documentation

---

.gitattributes

The Linguist stats on the bottom-right of the main page are incorrectly recognizing some files as SML; this fixes them to be OCaml instead.

Treat *.ml{i} in Linguist as OCaml, mark *.t as undetectable

---

src/document/comment.ml
src/document/doctree.ml
src/document/generator.ml
src/document/types.ml
src/document/utils.ml
src/html/generator.ml
src/latex/generator.ml
src/manpage/generator.ml
test/generators/html/Labels.html
test/generators/html/Markup.html
test/generators/html/Ocamlary.html
test/generators/html/Toplevel_comments-Comments_on_open.html
test/xref2/labels/labels.t/run.t

Fix https://github.com/ocaml/odoc/issues/613
The tooltip shows what would be rendered instead if no text was written. This is currently the original reference.
This is most useful for references that do not resolve, because the original reference is not visible at all.
The tooltip is generally easier to read than the target URL shown by the browser on hover and might benefit from smarter rendering of references in the future (eg. https://github.com/ocaml/odoc/issues/372)

Add a tooltip to references with text

---

CHANGES.md
src/odoc/compile.ml
test/sources/single_mli.t/run.t

Previously, the `--hidden` flag was used to set only the `Root.Odoc_file.compilation_unit` `hidden` field value.
Now, we also use it to set the `Lang.compilation_unit` `hidden` field value, so that they are in sync.
This allows to use the `--hidden` flag to not generate documentation, for instance when compiling a module solely to render its source (which happens for instance in the `single_mli` test, or in real life, `Astring` mli).

Fix hidden flag

---

src/document/comment.ml
src/ocamlary/ocamlary.mli
test/generators/html/Ocamlary.html
test/generators/latex/Ocamlary.tex
test/generators/man/Ocamlary.3o

Closes https://github.com/ocaml/odoc/issues/816 https://github.com/ocaml/odoc/pull/892
This is an alternative to https://github.com/ocaml/odoc/pull/892, which uses the recent `render_unresolved` function introduced in https://github.com/ocaml/odoc/pull/945.

Fix rendering of unresolved references

---

src/loader/doc_attr.ml
src/model/semantics.ml
src/model/semantics.mli
test/model/semantics/test.ml

Related issue: https://github.com/ocaml/odoc/issues/814
Most tags don't make sense in a page (deprecated, param, raise, ...) and the syntax prevents tags from being added in the middle of a page.
This adds a warning but do not disallow tags. It is important to not remove any text from pages and turning tags into paragraphs would not add anything interesting.

Warn against tags in pages

---

odoc.opam
test/model/semantics/test.ml
test/xref2/canonical_nested.t/run.t
test/xref2/classes.t/run.t
test/xref2/deep_substitution.t/run.t

A minor change between yojson 1.7.0 and 2.0.0 caused our tests to break as the output was formatted slightly differently. This attempts to fix that by doing compact output in some places and piping through jq in others.

Make the tests more robust to changes to yojson

---

src/document/renderer.ml
src/document/types.ml
src/document/url.ml
src/document/url.mli
src/html/generator.ml
src/latex/generator.ml
src/manpage/generator.ml
src/model/lang.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model_desc/paths_desc.ml
src/odoc/bin/main.ml
src/odoc/compile.ml
src/odoc/html_page.ml
src/odoc/html_page.mli
src/odoc/rendering.ml
src/odoc/source_tree.ml
src/xref2/component.ml
src/xref2/link.ml
test/pages/assets.t/index.mld
test/pages/assets.t/run.t
test/pages/assets.t/test.mli

Context: #59 , #972
**No support for referring to assets yet.**
This only provides a way to get odoc to place them "in the right place" in the directory structure; so it's only marginally useful.
Current interface:
- children given to `odoc compile` can now be of the form `asset-filename`
- `html-generate` and `html-targets` commands now accept `--asset FILE` arguments, which are paired (based on filename) with the relevant child asset. Warnings are emitted for unknown and missing assets.
- files passed to `html-generate` through `--asset` are copied in the directory of their parent; would it be better to put them in an `_assets` subdirectory?
This is illustrated in `test/pages/assets.t/run.t`

Rudimentary support for assets

---

odoc.opam

The version 1.6.0 contains a breaking change that we rely on.
This was caught by ocaml-ci's lower-bound check.

Update version constraint on Yojson

---

src/html_support_files/dune

Currently, regenerating support files requires using the test rule, which feels weird because changing the css has very little to do with tests. It also allows to generate the support files without running the test more easily.

Creates a dedicated rule to generate support files

---

doc/driver.mld

The first commit comment-out a command that should have been.
The second commit gives predictable and useful names to landmarks output files. Previously, names contained random numbers.
The third commit adds a benchmarks: The time spent running the slowest command. This metric might help recognize large performance regressions in rare cases that we might have missed otherwise.

Improvements to benchmarks and profiling

---

.github/workflows/changelog.yml

Add a changelog check in CI, to avoid having to do #1008 before releasing.
To disable the check on a PR, we should add the "no changelog" label.

Add changelog check in CI

---

CHANGES.md
src/document/generator.ml
test/generators/html/Ocamlary.html
test/generators/latex/Ocamlary.tex
test/generators/man/Ocamlary.3o

Print 'private' keyword for private type extensions

---

odoc-parser.opam

Since the `dune-project` file now has
```
(lang dune 3.7)
```
it generates a warning to build the odoc parser with a too old version of dune.

Update odoc-parser's constraint on dune

---

doc/driver.mld
doc/library_mlds/odoc_parser.mld

The parser's doc were not included anywhere since the remerge.
This PR simply includes the parser in the list of modules built by the driver.

Reference driver: Generate docs for the parser module

---

CHANGES.md
src/loader/cmi.ml

Cherry pick changes from https://github.com/ocaml/odoc/pull/1018, without the file rename.

Handle differences in sig_class for OCaml 5.1. (to `v2.3` branch)

---

CHANGES.md
doc/ocamldoc_differences.mld
doc/odoc_for_authors.mld
src/document/comment.ml
src/document/url.ml
src/loader/implementation.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model/reference.ml
src/model_desc/paths_desc.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/env.ml
src/xref2/env.mli
src/xref2/ref_tools.ml
src/xref2/shape_tools.ml
test/xref2/github_issue_932.t/foo.mli
test/xref2/github_issue_932.t/run.t

Fix #932
Not working yet, I've written most of the boring code, some tweaking is needed to make it work.
- the `ExtensionDecl` reference is added in Env
- I think the lookup code in Ref_tools is correct
- what is found in the Env is a `Extension` anchor, despite adding an `ExtensionDecl`
I think it's due to using `Extension.t` in the `extension_decl` type in Component:
```
type extension_decl =
[ `ExtensionDecl of Identifier.Extension.t * Extension.Constructor.t ]
```
but changing everything creates too many changes. On the opposite side, it's probably possible to refactor the types, as maybe the existing `Extension` type might be enough in a lot of places, but I'm not familiar enough with the code to tell.
Ideas are welcome!

Fix references to extension declarations

---

odoc.opam

Since table support, odoc is incompatible with tyxml 4.3.0.
See https://github.com/ocaml/opam-repository/pull/24686.

Update tyxml constraint

---

CHANGES.md
src/loader/cmi.ml

Cherry pick changes from #1018.
Is everyone happy with me not picking the rename from `cmi.ml` to `cmi.cppo.ml`?

Handle differences in sig_class for OCaml 5.1. (to master branch)

---

src/document/url.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model_desc/paths_desc.ml
src/xref2/compile.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/cpath.ml
src/xref2/errors.ml
src/xref2/find.ml
src/xref2/find.mli
src/xref2/ident.ml
src/xref2/lang_of.ml
src/xref2/lang_of.mli
src/xref2/link.ml
src/xref2/tools.ml
src/xref2/tools.mli
test/xref2/lib/common.cppo.ml

The ability to resolve those path will be useful in many render source code new features. In particular, this is a prerequisite to #976.

Add value and constructor path

---

src/xref2/ident.ml

This function is called a very large amount of times. Surprisingly, it was calling the generic compare function.
This has a very small impact.

Micro-optimize Ident.compare

---

doc/parent_child_spec.mld

This convention is already in use by Odig, Voodoo and Dune. It needs to be specified as it needs to change in order to support assets and complex hierarchies.

Doc: parent-child convention for installed packages

---

dune

The default alias will build every target known to dune. Since the addition of benchmarking, the rule running the reference driver does have a target, and was runned at each invokation of `dune build` in the root of the project.
This makes the default rules of the root directory an alias for the default rule of the `src` directory, avoiding running the reference driver too often (it also removes some rules in test from the root default alias).

Avoid running the reference when running `dune build` at the root of the project.

---

CHANGES.md
src/parser/parse_error.ml
src/parser/syntax.ml
src/parser/test/test.ml
src/parser/test/test_tables.ml
test/model/semantics/test.ml

Fixes https://github.com/ocaml/odoc/issues/1043

Warn when a table is not closed

---

CHANGES.md
src/loader/cmi.ml
src/loader/cmti.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model/reference.ml
src/xref2/compile.ml
src/xref2/component.ml
src/xref2/component.mli
src/xref2/env.ml
src/xref2/env.mli
src/xref2/ident.ml
src/xref2/lang_of.ml
src/xref2/lang_of.mli
src/xref2/link.ml
src/xref2/ref_tools.ml
src/xref2/tools.ml
test/model/semantics/test.ml
test/xref2/github_issue_447.t/a.mli
test/xref2/github_issue_447.t/run.t
test/xref2/refs/refs.md

Fix #447.
Currently, it is not possible to refer to constructors without specifying the parent type, except if they are in scope.
This PR fixes this by extending parents of constructor references to signatures.
The first commit adds the test. The second fixes the issue similarly to what it is done with `field` (which already allows omitting the type parent). The last two commits are refactoring that improve the guarantee given by the subtyping.
(Made with @EmileTrotignon)

Allow to omit parent type in constructor reference.

---

src/html_support_files/odoc.css

It used to be that the when following a link to an anchor, the anchor would appear a the top of the view, which was under the new search bar. This adds a margin of a 100px to such jumps.

fixes anchor appearing bellow search bar

---

src/parser/test/dune

This is broken since https://github.com/ocaml/odoc/pull/1061 as I focused on tests and forgot to try building without.
Related dune issue: https://github.com/ocaml/dune/issues/4738

Don't make parser tests installable

---

doc/driver.mld
doc/odoc.mld

This page lists the internal libraries and is generated by the driver. It's live in the v2.4 branch: https://ocaml.github.io/odoc/api_reference.html

doc: Add the generate page 'API Reference'

---

src/xref2/subst.ml
src/xref2/subst.mli
src/xref2/tools.ml

A small optimization + cleanup found while working on the sig optimization.

Don't compute the unused list removed_items in Tools.fragmap

---

README.md

Changes the path to `index.html` in the README.md to match the path in the [odoc documentation](https://ocaml.github.io/odoc/odoc_for_authors.html).

docs: fix path to index.html in README.md

---

CHANGES.md
src/odoc/odoc_link.ml
src/odoc/rendering.ml
test/integration/json_expansion_with_sources.t/run.t
test/sources/double_wrapped.t/run.t
test/sources/lookup_def_wrapped.t/run.t
test/sources/single_mli.t/run.t
test/xref2/module_preamble.t/run.t

Hidden modules stopped creating an output file with "render source code", since calling `html-generate` on them was used to generate the associated source code.
However, this breaks dune rules in some cases (see issue #1013), as dune always expect an output to the execution of the command. See #1013 for a case where it happens.
With the separation of implementation and interface pipelines (see #1067), we will stop generating those content-empty files when rendering source code.
I think this fix should be included as a hotfix to the `2.3` and `2.4` branches, to maintain compatibility with dune rules (and ensure `eio` can build its doc).
@talex5 could you confirm that this patch fixes your issue?

Revert to outputing a content-empty file when rendering a hidden module

---

CHANGES.md
src/html_support_files/odoc.css
src/odoc/rendering.ml
test/search/html_search.t/run.t
test/sources/source.t/a.ml
test/sources/source.t/run.t

This PR changes the color theme in odoc to match the gruvbox color set ( https://github.com/morhetz/gruvbox )
The dark theme looks like that : 
And the light theme like that : 
It was inspired by issue #1020 , but does more than what was asked there.

change color to gruvbox theme

---

src/model/names.ml
src/xref2/shape_tools.cppo.ml
test/sources/source.t/run.t

Looking up non-existent things in shapes takes ages - don't do it!

fix to shape lookup of missing items

---

doc/driver.mld

This should help consumers of the search engine index.
I noticed that the source for the `odoc_json_index` library is not rendered...

Adding documentation on json search index format

---

CHANGES.md
src/html_support_files/odoc.css

Add clock emoji before 'since' tag

---

CHANGES.md
src/document/doctree.ml

The preamble was not traversed when looking for math elements, resulting in a faulty math detection. Fix #1092.

Fix missing headers for katex

---

CHANGES.md
src/loader/cmi.ml
src/loader/cmt.ml
src/loader/cmti.ml
src/loader/ident_env.cppo.ml
src/loader/typedtree_traverse.ml
src/model/compat.cppo.ml
src/xref2/shape_tools.cppo.ml
test/xref2/lib/common.cppo.ml

This PR makes the minimal changes for supporting OCaml 5.2, without taking advantages of any of the new shape features in OCaml 5.2.0 .
Another aspect that should probably be improved later on is the support for `open`s in type expressions: the present PR is only traversing the open while it could be useful to keep track of those when generating the documentation:
```ocaml
val add:  Int.( t -> t -> t)
```

Basic support for OCaml 5.2.0

---

CHANGES.md
doc/odoc_for_authors.mld
src/parser/lexer.mll
src/parser/test/test.ml
test/generators/cases/markup.mli
test/generators/html/Markup.html
test/generators/latex/Markup.tex
test/generators/man/Markup.3o
test/model/semantics/test.ml

To summarize:
- A newline followed by any whitespaces should be considered to be one space character by odoc-parser and ocamlformat.
Consecutive whitespaces not after a newline are conserved as they are.
- Trim whitespaces at the beginning and end of code spans. Not related to the issue but as we making whitespaces a bit less significant, this is worth mentioning.

Normalize whitespaces in codespans

---

CHANGES.md
src/document/generator.ml
src/xref2/link.ml
test/generators/html/Stop_dead_link_doc.html
test/generators/latex/Stop_dead_link_doc.tex
test/generators/man/Stop_dead_link_doc.3o
test/xref2/hidden_representations.t/run.t
test/xref2/hidden_representations.t/test.mli

Instead of omitting variant constructors where they've got hidden elements in their types, we now show all constructors and just emit a warning when we detect the problem.
In addition, also check the fields of records similarly.

Treat hidden representations differently

---

CHANGES.md
src/loader/ident_env.cppo.ml

This is related to issue #1066, which was partially fixed by #1082. This PR sorts the remaining two instances of the problem: exceptions and type extensions.
Fixes #1095

Fix problem with exceptions and type extensions in extended opens

---

CHANGES.md
src/xref2/shape_tools.cppo.ml

This PR amends to the support for OCaml 5.2.0 to the updated version of the `Shape_reduce` queries API.

5.2.0 support and shape: use amended query API

---

doc/cheatsheet.mld
doc/driver.mld
doc/dune
doc/odoc.mld
doc/odoc_for_authors.mld

This adds a cheatsheet to the odoc manual. Have a look at the rendered page [here](https://choum.net/panglesd/odoc_cheatsheet/cheatsheet.html).
The cheatsheet is rendered by odoc, which is not really focused on rendering cheatsheets, so it does not render ideally well.
If someone wants to contribute by adding some special css on this page to make it better, feel free!

Add cheatsheet to the odoc manual

---

doc/cheatsheet.mld

Reported in https://discuss.ocaml.org/t/ann-odoc-syntax-cheatsheet/14658/5
Is there any other typo in this small document?

Fix yet another typo in cheatsheet

---

doc/driver.mld
src/document/ML.mli
src/document/generator.ml
src/document/generator_signatures.ml
src/document/reason.mli
src/loader/implementation.ml
src/loader/implementation.mli
src/loader/odoc_loader.ml
src/loader/odoc_loader.mli
src/model/lang.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model/root.ml
src/model_desc/lang_desc.ml
src/odoc/bin/main.ml
src/odoc/occurrences.ml
src/odoc/rendering.ml
src/odoc/resolver.ml
src/odoc/source.ml
src/xref2/shape_tools.cppo.ml
test/occurrences/double_wrapped.t/run.t
test/sources/source.t/run.t

`--source-id` is only needed when rendering implementations. However, compiling implementations can also be required for another feature: counting occurrences.
This PR makes `--source-id` option at compile time, but it remains mandatory to render source code.

Make `--source-id` optional when compiling implementations

---

CHANGES.md
src/html_support_files/odoc.css

This fixes the gap in between the preamble and the content without changing other margins, or changing the structure of the HTML.

Remove margin of first child of odoc-content

---

CHANGES.md
src/xref2/tools.ml
test/generators/html/Include2.html
test/generators/html/Ocamlary-FunctorTypeOf-argument-1-Collection.html
test/generators/html/Ocamlary-Recollection-argument-1-C.html
test/generators/html/Ocamlary-Recollection.html
test/generators/html/Ocamlary-module-type-A-Q.html
test/generators/html/Ocamlary-module-type-A.html
test/generators/html/Ocamlary-module-type-B-Q.html
test/generators/html/Ocamlary-module-type-B.html
test/generators/html/Ocamlary-module-type-C-Q.html
test/generators/html/Ocamlary-module-type-C.html
test/generators/html/Ocamlary-module-type-COLLECTION.html
test/generators/html/Ocamlary-module-type-MMM-C.html
test/generators/html/Ocamlary-module-type-MMM.html
test/generators/html/Ocamlary.html
test/generators/latex/Include2.tex
test/generators/latex/Ocamlary.FunctorTypeOf.tex
test/generators/latex/Ocamlary.Recollection.tex
test/generators/latex/Ocamlary.tex
test/generators/man/Include2.3o
test/generators/man/Ocamlary.3o
test/generators/man/Ocamlary.FunctorTypeOf.3o
test/generators/man/Ocamlary.Recollection.3o
test/xref2/dune
test/xref2/include_module_type_of_preamble.t/bar.ml
test/xref2/include_module_type_of_preamble.t/foo.mli
test/xref2/include_module_type_of_preamble.t/run.t
test/xref2/module_list.t/run.t

A module's `doc` field was propagated through expansions by synthetizing a comment at the top of the expanded signature. It's now propagated via the `doc` field of the signature.
In the case where the module has a comment and the signature has a top-comment, the module's comment is not propagated.
This fixes doc appearing multiple time when the signature is expanded mutliple time (eg. due to an include-module-type-of) and doc appearing when they shouldn't (eg. in a non-inline include).
This also moves the preambles into the right section in the generated HTML.

Remove unwanted or duplicate doc in expansions

---

src/driver/packages.ml

Pages installed in subdirectories of `<opam prefix>/doc/<pkg>/odoc-pages/` should have the subdirectories reflected in their parent IDs.

Driver: Fix hierarchical pages being given wrong parent id

---

README.md

I've been asked to review and improve the `odoc` documentation, website, and place in the OCaml Manual. Since much of my work is line editing, it can be helpful to make me code owner so I can edit little things like formatting and grammar without having to bother other maintainers and make a lot of noise, if you feel comfortable doing so. I am already code owner on ocaml.org and Dune, among others. So if you find it beneficial, you won't get little formatting changes in a PR again. 
If there are any major changes or suggestions that could alter the meaning, I would always consult with an engineer and open a PR.

minor formatting for `odoc`

---

CHANGES.md
src/parser/lexer.mll
src/parser/test/test.ml

This fixes https://github.com/ocaml/odoc/issues/1137 by implementing @panglesd's suggestion.
The syntax for code blocks with a result section is now:
{delim@lang[ code ]delim[ result ]}
Note: The terminating ]} do not contain the delimiter.

parser: Don't accept code block results without delim

---

src/parser/test/test.ml

I merged #1149 and realized only after that the formatting CI did not pass...
Fixing that here.

Fix fmt for parser test

---

CONTRIBUTING.md

In li.29, I get the following error:
```
[ERROR] Package conflict!
* Missing dependency:
- odoc-parser >= dev
no matching version
```
I followed the code from the top of this page. I'm I doing something wrong, or is there a missing step in here?
In li.84, is that version still correct or is there a more recent version now?

Line editing Contributing.md

---

CHANGES.md
odoc-driver.opam
src/driver/cmd_outputs.ml
src/driver/compile.ml
src/driver/compile.mli
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/packages.ml
src/driver/packages.mli
src/driver/sherlodoc.ml
src/model/fold.ml
src/model/fold.mli
src/model/paths.ml
src/model/paths.mli
src/odoc/bin/main.ml
src/odoc/fs.mli
src/odoc/indexing.ml
src/odoc/indexing.mli
src/odoc/odoc_file.ml
src/odoc/odoc_file.mli
src/search/json_index/json_search.ml
src/search/json_index/json_search.mli
test/search/html_search.t/run.t
test/search/id_standalone_comments.t/run.t
test/search/module_aliases.t/run.t

This PR adds a new marshalled output for the generation of index files.
This is desirable for several reasons:
- It allows to combine several pre-built indexes, making the index generation more incremental
- It can be read by other OCaml tools using odoc as library, for instance when building a search engine index (cc @EmileTrotignon). #1022 is also relevant.
The first commit fixes a bug in the computation of the ID of the page containing a standalone comment. The second commit is the actual change.
There are some design to discuss:
- This PR adds a `--marshall` flag to the `compile-index`: by default the output is json, but it is marshalled with this flag.
- The files containing marshelled indexes have to be prefixed by `index-` and have to have the `.odoc` extension.
- Currently, the …

Add a marshalled output for index generation

---

CHANGES.md
src/document/comment.ml
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model/reference.ml
src/model_desc/paths_desc.ml
src/xref2/component.ml
src/xref2/errors.ml
src/xref2/ref_tools.ml
test/model/semantics/test.ml

Add the parsing of references to pages and modules containing a slash: `{!./foo}`, `{!/foo}`, `{!//foo}`. 
These are not resolved yet.

Parsing of path-references to pages and modules

---

CHANGES.md
doc/ocamldoc_differences.mld
doc/odoc_for_authors.mld

#1115 was merged without a changelog entry and some updates to the doc. This adds them!

Added docs and changelog entry for polymorphic variants resolving

---

src/driver/dune

Add the odoc package as a deps to the driver, because it is one.
Now when you do `dune exec odoc_driver -- -p ...` before doing `dune build`, it works anyway !

add odoc package as a link deps to the driver

---

CHANGES.md
src/odoc/bin/main.ml
src/odoc/fs.ml
src/odoc/fs.mli
src/odoc/indexing.ml
src/odoc/resolver.ml
src/odoc/resolver.mli
src/utils/odoc_utils.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/errors.ml
src/xref2/link.ml
src/xref2/ref_tools.ml
test/integration/dune
test/parent_id/parent_id.t/file.mld
test/parent_id/parent_id.t/run.t
test/parent_id/sidebar.t/file.mld
test/xref2/path_references.t/doc/dup.mld
test/xref2/path_references.t/doc/foo.mld
test/xref2/path_references.t/doc/subdir/bar.mld
test/xref2/path_references.t/doc/subdir/dup.mld
test/xref2/path_references.t/run.t
test/xref2/path_references.t/test.ml

This implements the resolving of some path-references using the new `Named_roots` mechanism recently added.
This is work in progress. Currently, current-package and absolute references are resolved from pages. On top of https://github.com/ocaml/odoc/pull/1142

Path-references lookup to pages

---

test/xref2/big_search_path.t/run.t
test/xref2/dune

Was too brittle: too many false positive in CI...
(I rebuilded the debian-12-5.2_s390x_opam-2.1 ocaml-CI job on several PR).
I kept the test as a reminder to add it as part of a potential benchmark CI.

Disable "big search path" test.

---

src/html_support_files/odoc.css
test/parent_id/sidebar.t/run.t

There are now a lot of bars in odoc, which can be side, search or absent or present.
This fixes weird css interactions in with some combinations in that were merged before we had a chance to fix them in the sidebar pr.

Fix interaction between search and side bars

---

CHANGES.md
src/odoc/resolver.ml
src/utils/odoc_utils.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/ref_tools.ml
test/xref2/path_references.t/doc/foo.mld
test/xref2/path_references.t/run.t
test/xref2/path_references.t/test.ml

The code for resolving path-references is factorized into the `lookup_path` function. The `Named_roots` for libraries is used to locate modules. `Env`'s API is changed to make the `Ref_tools` part easier to write.
Unprefixed references are resolved both as pages and modules concurrently and a warning is generated if the reference is ambiguous.

Resolve path references to modules

---

CHANGES.md
src/loader/cmi.ml
test/generators/cases/bugs.ml
test/generators/html/Bugs.html
test/generators/latex/Bugs.tex
test/generators/man/Bugs.3o

Currently, generating documentation from ml files
```ocaml
(* test.ml *)
let repeat x y = x ,y, x, y
```
makes odoc misprint equal type variables as distinc type variables:
```ocaml
val repeat : 'a -> 'b -> 'c * 'd * 'e * 'f
```
starting from OCaml 4.14 .
This issue stems from the uses of physical equalities on non-representative type expressions in the name map of the type expression loader of odoc. Consequently, different type nodes are attributed different names by odoc, even if they belong to the same class of equal-after-unification type nodes. 
This issue typically doesn't arise when using mli files, because then we read source type expressions directly, without doing any unification (in most cases?).
This PR fixes this issue by ensuring that the naming maps only use representative …

Fix the type_expr loader in OCaml 4.14 and later

---

odoc-driver.opam
src/driver/compile.ml
src/driver/compile.mli
src/driver/dune
src/driver/dune_style.ml
src/driver/dune_style.mli
src/driver/indexes.ml
src/driver/library_names.ml
src/driver/library_names.mli
src/driver/ocamlfind.ml
src/driver/ocamlfind.mli
src/driver/ocamlobjinfo.ml
src/driver/ocamlobjinfo.mli
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/packages.ml
src/driver/packages.mli
src/driver/run.ml
src/driver/sherlodoc.ml
src/driver/stats.ml
src/driver/voodoo.ml
src/driver/voodoo.mli
src/loader/odoc_loader.ml
src/odoc/bin/main.ml
src/odoc/classify.cppo.ml

adds two new modes to the driver for different inputs - one to handle voodoo-style layout, and the second to handle dune `_build` style layout.

Voodoo odoc driver

---

CHANGES.md
src/document/comment.ml
src/document/url.ml
src/model/names.ml
src/model/names.mli
src/model/paths.ml
src/model/paths.mli
src/model/paths_types.ml
src/model/reference.ml
src/model/root.ml
src/model_desc/paths_desc.ml
src/odoc/asset.ml
src/odoc/html_page.ml
src/odoc/resolver.ml
src/search/json_index/json_search.ml
src/xref2/component.ml
src/xref2/env.ml
src/xref2/env.mli
src/xref2/errors.ml
src/xref2/ref_tools.ml
test/xref2/path_references.t/doc/foo.mld
test/xref2/path_references.t/run.t

Parse and resolve asset references

---

src/driver/compile.ml
src/driver/compile.mli
src/driver/dune_style.ml
src/driver/indexes.ml
src/driver/odoc.ml
src/driver/odoc_driver.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/packages.ml
src/driver/packages.mli
src/driver/stats.ml
src/driver/voodoo.ml
src/driver/worker_pool.ml

The original reason for this is to allow adding odoc units that are not part of a package (eg pages that list packages, ...).
But I think it also makes it more readable:
- It factors path computations from the various "package extractors"[^1], in the end they have less things to do,
- The paths for an odoc unit are computed once, all at the same place, in a place which does nothing else,
- Understanding the code that runs commands is much simpler, since it has less things to do (run every command once and in the right order).
Indexes yet have to be implemented, so this PR is not finished yet.
[^1]: By "package extractors" I mean the `of_libs` function (creating packages from the opam switch), the `of_dune_build` function (creating packages from `_build/default/...`) and the `of_voodoo` …

Driver: Separate types for "package" and "odoc unit".

---

doc/driver.mld
doc/ocamldoc_differences.mld

Line edit ocamldoc differences

---

doc/features.mld

Line editing for `features.mld`, mostly formatting, grammar, syntax, etc.
I changed several module type expressions to module-type expressions, as it seems "module type" was the adjective for "expression," based on the header Module Types. If it's "module" "type expressions," where "module" is modifying "type expressions," I'll change them back to "module type expressions."

line edit features.mld

---

src/driver/compile.ml
src/driver/dune
src/driver/landing_pages.ml
src/driver/landing_pages.mli
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/util.ml
src/html/link.ml
src/odoc/asset.ml
src/odoc/asset.mli
src/odoc/bin/main.ml
src/odoc/compile.ml
src/odoc/compile.mli
src/odoc/source.ml
test/parent_id/dune
test/parent_id/empty_parent_id.t/run.t

This adds generation of (basic) pages for:
- A "list of all packages" page (at the root of the doc)
- A landing page for each package (in the `<pkgname>/` folder)
- A landing page for the list of libraries (in the `<pkgname>/lib/` folder)
- A landing page for each library (in the `<pkgname>/lib/<libname>` folder)
This PR does not touch only the driver: I had to add the possibility of an empty `--parent-id` for the "list of all packages" page.
I also had to avoid "relative references" in the generated pages as they are did not resolve. I used `rooted absolute references instead, and I will investigate the bug.
This will hopefully be useful to test various ideas for the breadcrumbs.

Driver: generate "external" pages

---

CHANGES.md
src/model/comment.ml
src/model/dune
src/model/frontmatter.ml
src/model/lang.ml
src/model/root.ml
src/model/root.mli
src/model_desc/lang_desc.ml
src/odoc/compile.ml
src/odoc/html_fragment.ml
test/pages/frontmatter.t/one_frontmatter.mld
test/pages/frontmatter.t/run.t
test/pages/frontmatter.t/two_frontmatters.mld
test/pages/frontmatter.t/zero_frontmatter.mld

This PR adds a frontmatter to mld pages.
The frontmatter consists in this PR to a list of string key values. Code blocks of the form:
```
{@meta[
key1: value1
key2: value2
]}
```
are removed from the content and the key-value pairs are added to the frontmatter of the page.
The frontmatter is added to the odoc file, including the page's "root", allowing to access it quickly without loading the whole content.
---
The idea of having a frontmatter originates from https://github.com/ocaml/odoc/discussions/1097 (see the "Metadata block" section).
In this discussion, the metadata provided by the frontmatter is:
- The package and library dependencies of the page (to be able to do cross-package referencing)
- The order in the table of content, for index pages.
The parsing of the data is not …

Add a frontmatter to mld pages

---

CHANGES.md
src/html/config.ml
src/html/config.mli
src/html/generator.ml
src/html/html_fragment_json.ml
src/html/html_page.ml
src/html/link.ml
src/html/link.mli
src/odoc/bin/main.ml
src/odoc/html_fragment.ml
src/search/html.ml
test/integration/remap.t/otherlib.mli
test/integration/remap.t/run.t
test/integration/remap.t/test.mli

This is to allow the publishing of 'partial docsets' - the idea being that the driver proceeds as usual up until HTML generation, and at that point only generates HTML pages for the packages you wish to publish on your site, and remap links to other packages to ocaml.org or other site.

Add the ability to remap identifiers during HTML generation

---

odoc-driver.opam

The driver depends on sherlodoc, this should be reflected in the opam file. This is a first step in having the sherlodoc - odoc integration checked by CI.

The driver depends on sherlodoc

---

odoc-driver.opam

This reverts https://github.com/ocaml/odoc/pull/1197 as it breaks the CI and fixing it requires quite a bit of technology. The way ocaml-ci installs dependencies seems to be incompatible with having dependency of the form `local package -> other package -> local package`.

Revert "driver depend on sherlodoc"

---

odoc.opam

The output format of older yojson was unstable in some cases.

opam: Update lower bounds on yojson

---

src/loader/cmi.ml
src/loader/doc_attr.ml
src/syntax_highlighter/syntax_highlighter.ml
src/xref2/shape_tools.cppo.ml
test/xref2/lib/common.cppo.ml
test/xref2/module_preamble.t/run.t

Backport of https://github.com/ocaml/odoc/pull/1202 on the `v2.4` branch.

Compat with OCaml 5.3.0~alpha1

---

CHANGES.md
odoc-driver.opam
src/driver/compile.ml
src/driver/dune
src/driver/dune_style.ml
src/driver/landing_pages.ml
src/driver/library_names.ml
src/driver/library_names.mli
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/packages.ml
src/driver/packages.mli
src/driver/run.ml
src/driver/voodoo.ml
src/driver/voodoo.mli
src/odoc/bin/main.ml
src/odoc/classify.cppo.ml
src/odoc/fs.ml
src/syntax_highlighter/syntax_highlighter.ml
test/xref2/path_references.t/run.t

This PR contains the contents of #1192 as well as a few more bugfixes and improvements required to ensure we can use `odoc_driver` in place of voodoo for building the docs for ocaml.org. 
Best reviewed commit-by-commit.

Docs CI compatibility

---

src/document/sidebar.ml
src/utils/odoc_list.ml
src/utils/odoc_utils.ml
src/utils/tree.ml
src/utils/tree.mli

Reduce diff of #1220
Probably more could be put in this branch but my goal is to split #1220 as much as possible to make the diff digestable.
cc @panglesd for review (I don't have the repo rights to add reviewers anymore)

Define Tree and Forest modules for sidebars and index

---

src/document/url.ml
src/document/url.mli

I often have to look at the implementation to understand why the return type is `result`, and if I can assert that it will return `Ok`...
This does not fix the API but helps future me and others when using this function.
Extracted from #1220.

Document `Url.from_identifier` result return type

---

CHANGES.md
README.md
odoc-md.opam
src/driver/compile.ml
src/driver/dune_style.ml
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/odoc_units_of.ml
src/driver/packages.ml
src/driver/packages.mli
src/driver/voodoo.ml
src/markdown/doc_of_md.ml
src/markdown/doc_of_md.mli
src/markdown/dune
src/markdown/odoc_md.ml
src/odoc/compile.ml

This PR adds a new package, `odoc-md`, that can process markdown files and output `page-*.odoc` files to be linked and then turned into HTML/man/whatever by `odoc`. It's based on previous work by @dbuenzli and @panglesd, but is more limited in scope. There is no support for odoc-style references in markdown, as the main intent is to be able to render the various markdown-formatted files that `voodoo` currently does for ocaml.org (e.g. https://ocaml.org/p/odoc/latest/README.md.html).
`odoc-md` is based on [cmarkit](https://erratique.ch/software/cmarkit), which has an OCaml lower bound of 4.14, which is why this is a new package rather than part of the odoc package.

Standalone markdown support

---

src/driver/cmd_outputs.ml
src/driver/compile.ml
src/driver/compile.mli
src/driver/landing_pages.ml
src/driver/library_names.ml
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/odoc_units_of.ml
src/driver/odoc_units_of.mli
src/driver/packages.ml
src/driver/sherlodoc.ml
src/driver/voodoo.ml
src/driver/voodoo.mli
src/odoc/bin/main.ml
src/odoc/resolver.ml
src/odoc/resolver.mli
test/xref2/path_references.t/run.t

Combined with the splitting of the compile/link phases so we can link to more than just the dependencies of your package. This is a building block to allow links in the documentation of package A to go to package B that isn't a direct dependency - or even to package C that depends on package A!

Voodoo fixes following the change in layout

---

src/driver/dune
src/driver/opam.ml

Packages without the corresponding files (eg installed by `dune install`) do not have the `<packagename>.change` file, making `odoc_driver` fully crash.
Moreover their is a missing dependency on `odoc-md` (which could have been part of the `odoc-driver` package?)

Fix dep issue and hard failure

---

doc/odoc_for_authors.mld

I decided to add some docs on each construct (tags and light syntax list) on how they end.
The alternative would have been to factor that by adding a section on the different kind of blocks (nestable and non-nestable), and a section on implicit ending (blank line or non-nestable), and then, say that tags and light syntax lists are implicitly ended. That felt overkill!

Doc: improve doc on implicit ending of blocks

---

CHANGES.md
src/driver/common_args.ml
src/driver/compile.ml
src/driver/compile.mli
src/driver/dune_style.ml
src/driver/landing_pages.ml
src/driver/odoc.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/odoc_units_of.ml
src/driver/odoc_units_of.mli
src/driver/packages.ml
src/driver/packages.mli
src/driver/voodoo.ml
src/html/link.ml
src/odoc/bin/main.ml
test/integration/remap.t/remap.txt
test/integration/remap.t/run.t

This adds a mode for publishing your package docs on your own site. It will generate HTML for the packages you select, and rewrite links that would have gone to other local packages to their documentation pages on ocaml.org.

Html remap

---

CHANGES.md
odoc-bench.opam
odoc.opam

The first two commits backports changes made in previous 2.4 patch releases.
I suggest that we only tag patch releases on the 2.4 branch to avoid confusion in the future.

Prepare for 2.4.4 release

---

CHANGES.md

Releases on the 2.4 were not reflected in the changelog.

Backport changelog from the 2.4 branch

---

src/driver/common_args.ml
src/driver/compile.ml
src/driver/compile.mli
src/driver/odoc_driver.ml
src/driver/packages.ml

- Avoid "hanging state" where computation happen but the user does not know what is going on,
- Fix wrong computation of the number of executed generation,
- Only generate JSON output if requested with `--generate-json` (@jonludlam let me know if you want me to revert this one, but it takes a bit of time when, for users, JSON output is not needed).

Improve driver experience

---

src/driver/common_args.ml
src/driver/compile.ml
src/driver/dune_style.ml
src/driver/odoc.mli
src/driver/odoc_driver.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/odoc_units_of.ml
src/driver/odoc_units_of.mli
src/driver/opam.ml
src/driver/opam.mli
src/driver/packages.ml
src/driver/packages.mli
src/driver/stats.ml
src/driver/voodoo.ml

Further voodoo

---

src/html_support_files/odoc.css

Since everyone is on holidays, I'm proposing CSS changes. These are small tweaks for the sidebar and source code pages.

CSS tweaks for the sidebar and source code page

---

CHANGES.md
src/html/generator.ml
src/html/html_fragment_json.ml
src/html/html_page.ml
src/html/sidebar.ml
src/model/comment.ml
src/model/names.ml
src/model/semantics.ml
src/ocamlary/dune
src/ocamlary/ocamlary.mli
src/odoc/compile.ml
src/utils/dune
src/utils/odoc_utils.ml
test/generators/gen_rules/gen_rules.ml
test/generators/html/Ocamlary-Op.html
test/generators/html/Ocamlary.html
test/generators/html/ocamlary.targets
test/generators/latex/Ocamlary.tex
test/generators/link.dune.inc
test/generators/man/Ocamlary.3o
test/generators/man/Ocamlary.Op.3o
test/generators/man/ocamlary.targets

Fix https://github.com/ocaml/odoc/issues/1253

 Add missing parentheses around identifier 'let*' 

---

src/driver/landing_pages.ml
src/driver/library_names.ml
src/markdown/doc_of_md.ml
src/markdown/odoc_md.ml
src/odoc/bin/main.ml

Some minor fixes

---

src/driver/global_config.ml
src/driver/global_config.mli
src/driver/opam.ml
src/driver/opam.mli
src/driver/packages.ml
src/loader/dune
src/odoc/bin/main.ml
src/odoc/compile.ml
src/odoc/compile.mli
src/odoc/fs.ml
src/odoc/fs.mli
src/odoc/resolver.ml
test/sources/lookup_def.t/run.t
test/xref2/warnings.t/run.t

- The custom-layout option is for 'monorepo mode'
- As is the short-title option
- The duplicates problem is causing bug in trunk right now
- The fix for Cmx_format is only helpful in 'monorepo mode'
- The versions thing and the global_config fixes come up when building in 'normal mode' when in a dune repo

More misc fixes

---

CHANGES.md
src/document/generator.ml
src/driver/run.ml
src/driver/worker_pool.ml
src/html/generator.ml
src/html/html_page.ml
src/html/html_source.ml
src/index/skeleton.ml
src/latex/generator.ml
src/loader/ident_env.cppo.ml
src/syntax_highlighter/syntax_highlighter.ml
src/utils/odoc_list.ml

This is enough to highlight `reason_parser.ml` in `reason.3.8.0`, which is one very large file that Odoc has to process.

Fix stack overflow when highlighting large source files

---

src/driver/bin/odoc_driver.ml
src/driver/bin/odoc_driver_monorepo.ml
src/driver/bin/odoc_driver_voodoo.ml
src/driver/compile.ml
src/driver/compile.mli
src/driver/odoc.ml
src/driver/odoc.mli
src/odoc/bin/main.ml
src/odoc/indexing.ml
src/odoc/indexing.mli
src/search/json_index/json_search.ml
src/search/json_index/json_search.mli
test/search/html_search.t/run.t
test/search/simplified_search.t/fuse.js.js
test/search/simplified_search.t/j.ml
test/search/simplified_search.t/main.ml
test/search/simplified_search.t/page.mld
test/search/simplified_search.t/run.t

This is for search on ocaml.org.

Simplified search index

---

test/model/semantics/dune
test/odoc_print/dune

The library is installable and is built when the tests are not going to be run.
This fails in the lower-bounds CI because of the requirement on yojson is not respected when the dependencies are installed with 'with-test'.
"yojson" {>= "2.1.0" & with-test}

test: Remove 'type_desc_to_yojson' library

---

CHANGES.md
src/html_support_files/odoc.css

this is for the package index pages with the titles that look like: **Package angstrom 0.16.1 [issues](https://github.com/inhabitedtype/angstrom/issues) [more…](#)**.
it appears that the new heading structure is something like this:
```html
<header class="odoc-preamble">
<h1 id="package-angstrom">
<a href="#package-angstrom" class="anchor"></a>
Package angstrom
<span class="version">0.16.1</span>
<nav>
<a href="https://github.com/inhabitedtype/angstrom/issues">issues</a>
<a href="#package_info">more…</a>
</nav>
</h1>
```
notably, the h1 element doesn't have a .package classname anymore which breaks the styling, reverting the version and links to the large title text size.
the new selectors are borrowed from the odig css.
https://github.com/b0-system/odig/blob/b0e7b144d921d345d49cf4958caab0 …

css: update selectors for odig package title

---

doc/odoc_for_authors.mld

doc: Mention links to current package docs

---

src/driver/bin/odoc_driver.ml
src/driver/bin/odoc_driver_voodoo.ml
src/driver/status.ml

This allows in ocaml.org to redirect the old links (`p/<pkgname>/<version>/<modulename>/`) to the new ones (`p/<pkgname>/<version>/<libraryname>/<modulename>/`).
To be combined with this (WIP) [branch](https://github.com/panglesd/v3.ocaml.org-server/tree/odoc-3.0).

Driver voodoo mode: generation of a `status.json` with a list of redirections

---

CHANGES.md
src/latex/generator.ml
src/latex/raw.ml
src/latex/raw.mli
src/latex/types.ml
test/pages/medias.t/index.mld
test/pages/medias.t/run.t

This  small PR adds support for images to the latex backed for png, pdf, and jpeg internal assets.
As a side-note, I am slightly surprised that there is no support for width information on the media tags since both image and video are hard to place properly without fixing their size.

Add png, pdf and jpeg image support to the latex backend

---

CHANGES.md
src/odoc/bin/main.ml

Don't backtrace on invalid input in compile-deps

---

CHANGES.md
src/html_support_files/odoc.css

Fix indentation bug with verbatim in tags

---

CHANGES.md
src/driver/bin/odoc_driver.ml
src/driver/opam.ml
src/driver/opam.mli

Driver: Check for missing/unknown opam packages

---

CHANGES.md
src/driver/compile.ml
src/driver/landing_pages.ml
src/driver/odoc_unit.ml
src/driver/odoc_unit.mli
src/driver/odoc_units_of.ml

So in the docs-ci, we don't have the 'prep' dir (with all the cmts/cmtis) for any package apart from the one being built. This is a problem for implementations of virtual libraries that aren't in the same package as the virtual library itself, as we try to copy the cmti from the virtual library to the implementation. 
The solution here it to copy _all_ cmtis for libraries without archives to the odoc dir. These will then be available to be used.

Further fixes for virtual libraries

---

CHANGES.md
src/html/generator.mli
src/odoc/html_fragment.ml

@dbuenzli could you please check this works for you? As a quick check, with this I get:
```
$ echo "{0:sample OCaml 4.11.1 sample package documentation}" > frag.mld 
$ dune exec -- odoc html-fragment frag.mld  
<h1 id="sample"><a href="#sample" class="anchor"></a>OCaml 4.11.1 sample package documentation</h1>
```

Fix issue #610 - `odoc html-fragment` not producing headings correctly

---

CHANGES.md
src/odoc/classify.cppo.ml

This breaks docs for at least rdbg.1.184.1

Fix classify when there are archives sharing modules

---

sherlodoc/store/storage_marshal.ml
src/driver/library_names.ml
src/odoc/bin/dune
src/odoc/bin/main.ml
src/odoc/classify.cppo.ml
src/odoc/fs.ml
src/odoc/html_fragment.ml
src/odoc/indexing.ml
src/odoc/occurrences.ml
src/odoc/odoc_file.ml
src/odoc/rendering.ml
src/odoc/sidebar.ml
src/odoc/support_files.ml
src/utils/odoc_utils.ml
test/generators/dune
test/generators/gen_rules_lib.ml
test/odoc_print/occurrences_print.ml
test/xref2/lib/common.cppo.ml

On top of https://github.com/ocaml/odoc/pull/1315
Remove many misuses of input and output channels.

Safer file handling

---

CHANGES.md
src/driver/odoc_units_of.ml

These warnings cannot be fixed by the user, therefore they serve no purpose.

Disable warnings coming from linking implementations

---

CONTRIBUTING.md

I am a newcomer to odoc. I have noticed that the API documentation links are broken. I updated them accordingly.
I think the text descriptions around the links might need some change as well, but I don't have the enough experience with odoc to carry that.

Update odoc API documentation links

---

CHANGES.md
doc/driver.mld
doc/odoc_for_authors.mld
src/driver/bin/odoc_driver.ml
src/driver/compile.ml
src/driver/odoc.ml
src/driver/odoc.mli

We currently only output warnings from the Link phase. This PR also outputs warnings from the compile phase, including those that come from the parser. 
This PR also fixes some warnings that this change made apparent.

Driver compile warnings

---

CHANGES.md
doc/dune
doc/odoc-parser-config.sexp
src/model/semantics.ml
src/parser/ast.ml
src/parser/lexer.mll
src/parser/odoc_parser.ml
src/parser/odoc_parser.mli
src/parser/test/test.ml

This PR is based on #1317. Only the last commit is new.
It makes the parser AST store raw content for code blocks and verbatim.
It exposes in the parser functions to get the processed content of those blocks.
The consumer are then responsible for processing the content (eg, odoc) or using the raw content (eg a tool building a file with line directives from specific code blocks).

Store raw content of code blocks in parser's AST

---

CHANGES.md
src/.ocamlformat-ignore
src/loader/doc_attr.mli
src/loader/odoc_loader.ml
src/loader/odoc_loader.mli
src/markdown/doc_of_md.ml
src/odoc/bin/main.ml
src/odoc/dune
src/odoc/extract_code.cppo.ml
src/odoc/extract_code.ml
src/odoc/extract_code.mli
src/parser/ast.ml
src/parser/lexer.mli
src/parser/lexer.mll
src/parser/odoc_parser.ml
src/parser/parse_error.ml
src/parser/test/test.ml
src/parser/token.ml
test/extract_code/cmti_extraction.t/main.mli
test/extract_code/cmti_extraction.t/run.t
test/extract_code/dune
test/extract_code/error.t/run.t
test/extract_code/mld_extraction.t/main.mld
test/extract_code/mld_extraction.t/run.t

This is an early prototype (on top of #1325) of an `extract-code` command, which extracts named code blocks into a file. Supersedes the venerable #303.
This demonstrates that the location is right:
`test.mld`:
```
{0 hello}
{[
let f x = x +. 2.
]}
{[ let x = f 2
]}
```
```
$ dune exec -- odoc extract-code test.mld > ocaml.ml
$ ocaml ocaml.ml
File "test.mld", line 10, characters 16-17:
Error: This expression has type int but an expression was expected of type
float
Hint: Did you mean 2.?
```

Extract code blocks by name

---

CHANGES.md
sherlodoc/db/dune
sherlodoc/query/dune
sherlodoc/store/dune

This is so we can compile the web server of sherlodoc outside of odoc.

Expose sherlodoc libraries

---

src/markdown/doc_of_md.ml

Fix #1356. 
I have confirmed that this now renders the [problematic example](https://github.com/codex-semantics-library/patricia-tree/blob/main/README.md) correctly. However, running `dune test` failed with lots of diffs which seem unrelated to this PR's changes.

Fix extra quote added after images

---

dune-project
odoc-bench.opam
odoc-driver.opam
odoc-md.opam
odoc-parser.opam
odoc.opam
test/generators/dune

Hello,
You are currently calling `dune format-dune-file` from one of your tests. This command does not honour the Dune lang version used in the project which means that your test will break whenever we change the formatting style in Dune.
In Dune 3.18 we introduced a built-in action `(format-dune-file <src> <dst>)` precisely for this purpose. This action honours the current Dune lang version and does not require shelling out to an external process.
Note that `dune format-dune-file` may evolve in ways that may not be backwards compatible in the near future (as the CLI interface does not have any backwards compatibility or versioning guarantees), so we are encouraging users of this command to switch to the action instead.
See https://github.com/ocaml/dune/pull/10892#issuecomment-2503530595 …

Use `(format-dune-file)` instead of `dune format-dune-file`

---

odoc-driver.opam
odoc.opam

Fpath 0.7.1 seems to have an odd interaction with the result library and dune, where sometimes the result library is omitted from the include path passed to ocaml. 0.7.3 is supported on all versions of OCaml that Odoc supports.

Add lower-bound constraint on fpath

---

CHANGES.md
src/document/comment.ml
src/document/generator.ml
src/model/paths.ml
src/model/paths.mli
src/odoc/url.ml
test/occurrences/double_wrapped.t/run.t

A while back we changed the type of `Path.Resolved.identifier` so we could return `None` for the case where there is genuinely no identifier that can be used. This was initially for to allow paths to core types to be resolved, even though there's no destination for them.
This commit extends this idea so that attempting to generate an identifier for a hidden path will result in `None`. Whilst we would prefer not to generate these paths at all, it can happen as a consequence of incorrect canonical paths.
Partial fix for #1369

Don't allow links to hidden pages

---

src/driver/opam.ml

See https://github.com/ocaml/opam/pull/6442
String.starts_with has been available since OCaml 4.13, so this change is fully backward compatible given that odoc-driver requires at least 5.1

Add support for opam 2.5
